
var WasmPitchModule = (() => {
  var _scriptDir = import.meta.url;
  
  return (
function(WasmPitchModule) {
  WasmPitchModule = WasmPitchModule || {};


var a;a||(a=typeof WasmPitchModule !== 'undefined' ? WasmPitchModule : {});var b,h;a.ready=new Promise(function(c,d){b=c;h=d});Object.getOwnPropertyDescriptor(a.ready,"_free")||(Object.defineProperty(a.ready,"_free",{configurable:!0,get:function(){k("You are getting _free on the Promise object, instead of the instance. Use .then() to get called back with the instance, see the MODULARIZE docs in src/settings.js")}}),Object.defineProperty(a.ready,"_free",{configurable:!0,set:function(){k("You are setting _free on the Promise object, instead of the instance. Use .then() to get called back with the instance, see the MODULARIZE docs in src/settings.js")}}));
Object.getOwnPropertyDescriptor(a.ready,"_get_pitch_mpm_c")||(Object.defineProperty(a.ready,"_get_pitch_mpm_c",{configurable:!0,get:function(){k("You are getting _get_pitch_mpm_c on the Promise object, instead of the instance. Use .then() to get called back with the instance, see the MODULARIZE docs in src/settings.js")}}),Object.defineProperty(a.ready,"_get_pitch_mpm_c",{configurable:!0,set:function(){k("You are setting _get_pitch_mpm_c on the Promise object, instead of the instance. Use .then() to get called back with the instance, see the MODULARIZE docs in src/settings.js")}}));
Object.getOwnPropertyDescriptor(a.ready,"___stdio_exit")||(Object.defineProperty(a.ready,"___stdio_exit",{configurable:!0,get:function(){k("You are getting ___stdio_exit on the Promise object, instead of the instance. Use .then() to get called back with the instance, see the MODULARIZE docs in src/settings.js")}}),Object.defineProperty(a.ready,"___stdio_exit",{configurable:!0,set:function(){k("You are setting ___stdio_exit on the Promise object, instead of the instance. Use .then() to get called back with the instance, see the MODULARIZE docs in src/settings.js")}}));
Object.getOwnPropertyDescriptor(a.ready,"onRuntimeInitialized")||(Object.defineProperty(a.ready,"onRuntimeInitialized",{configurable:!0,get:function(){k("You are getting onRuntimeInitialized on the Promise object, instead of the instance. Use .then() to get called back with the instance, see the MODULARIZE docs in src/settings.js")}}),Object.defineProperty(a.ready,"onRuntimeInitialized",{configurable:!0,set:function(){k("You are setting onRuntimeInitialized on the Promise object, instead of the instance. Use .then() to get called back with the instance, see the MODULARIZE docs in src/settings.js")}}));
var l=Object.assign({},a),m="object"==typeof window,n="function"==typeof importScripts,q="object"==typeof process&&"object"==typeof process.versions&&"string"==typeof process.versions.node,r=!m&&!q&&!n;if(a.ENVIRONMENT)throw Error("Module.ENVIRONMENT has been deprecated. To force the environment, use the ENVIRONMENT compile-time option (for example, -s ENVIRONMENT=web or -s ENVIRONMENT=node)");var t="",u,v,w,fs,x,y;
if(q){if("object"!=typeof process||"function"!=typeof require)throw Error("not compiled for this environment (did you build to HTML and try to run it not on the web, or set ENVIRONMENT to something - like node - and run it someplace else - like on the web?)");t=n?require("path").dirname(t)+"/":__dirname+"/";y=()=>{x};u=function(c,d){y();c=x.normalize(c);return fs.readFileSync(c,d?void 0:"utf8")};w=c=>{c=u(c,!0);c.buffer||(c=new Uint8Array(c));assert(c.buffer);
return c};v=(c,d,e)=>{y();c=x.normalize(c);fs.readFile(c,function(g,B){g?e(g):d(B.buffer)})};1<process.argv.length&&process.argv[1].replace(/\\/g,"/");process.argv.slice(2);process.on("uncaughtException",function(c){throw c;});process.on("unhandledRejection",function(c){throw c;});a.inspect=function(){return"[Emscripten Module object]"}}else if(r){if("object"==typeof process&&"function"===typeof require||"object"==typeof window||"function"==typeof importScripts)throw Error("not compiled for this environment (did you build to HTML and try to run it not on the web, or set ENVIRONMENT to something - like node - and run it someplace else - like on the web?)");
"undefined"!=typeof read&&(u=function(c){return read(c)});w=function(c){if("function"==typeof readbuffer)return new Uint8Array(readbuffer(c));c=read(c,"binary");assert("object"==typeof c);return c};v=function(c,d){setTimeout(()=>d(w(c)),0)};"undefined"!=typeof print&&("undefined"==typeof console&&(console={}),console.log=print,console.warn=console.error="undefined"!=typeof printErr?printErr:print)}else if(m||n){n?t=self.location.href:"undefined"!=typeof document&&document.currentScript&&(t=document.currentScript.src);
_scriptDir&&(t=_scriptDir);0!==t.indexOf("blob:")?t=t.substr(0,t.replace(/[?#].*/,"").lastIndexOf("/")+1):t="";if("object"!=typeof window&&"function"!=typeof importScripts)throw Error("not compiled for this environment (did you build to HTML and try to run it not on the web, or set ENVIRONMENT to something - like node - and run it someplace else - like on the web?)");u=c=>{var d=new XMLHttpRequest;d.open("GET",c,!1);d.send(null);return d.responseText};n&&(w=c=>{var d=new XMLHttpRequest;d.open("GET",
c,!1);d.responseType="arraybuffer";d.send(null);return new Uint8Array(d.response)});v=(c,d,e)=>{var g=new XMLHttpRequest;g.open("GET",c,!0);g.responseType="arraybuffer";g.onload=()=>{200==g.status||0==g.status&&g.response?d(g.response):e()};g.onerror=e;g.send(null)}}else throw Error("environment detection error");a.print||console.log.bind(console);var z=a.printErr||console.warn.bind(console);Object.assign(a,l);l=null;
Object.getOwnPropertyDescriptor(a,"arguments")||Object.defineProperty(a,"arguments",{configurable:!0,get:function(){k("Module.arguments has been replaced with plain arguments_ (the initial value can be provided on Module, but after startup the value is only looked for on a local variable of that name)")}});Object.getOwnPropertyDescriptor(a,"thisProgram")||Object.defineProperty(a,"thisProgram",{configurable:!0,get:function(){k("Module.thisProgram has been replaced with plain thisProgram (the initial value can be provided on Module, but after startup the value is only looked for on a local variable of that name)")}});
Object.getOwnPropertyDescriptor(a,"quit")||Object.defineProperty(a,"quit",{configurable:!0,get:function(){k("Module.quit has been replaced with plain quit_ (the initial value can be provided on Module, but after startup the value is only looked for on a local variable of that name)")}});assert("undefined"==typeof a.memoryInitializerPrefixURL,"Module.memoryInitializerPrefixURL option was removed, use Module.locateFile instead");assert("undefined"==typeof a.pthreadMainPrefixURL,"Module.pthreadMainPrefixURL option was removed, use Module.locateFile instead");
assert("undefined"==typeof a.cdInitializerPrefixURL,"Module.cdInitializerPrefixURL option was removed, use Module.locateFile instead");assert("undefined"==typeof a.filePackagePrefixURL,"Module.filePackagePrefixURL option was removed, use Module.locateFile instead");assert("undefined"==typeof a.read,"Module.read option was removed (modify read_ in JS)");assert("undefined"==typeof a.readAsync,"Module.readAsync option was removed (modify readAsync in JS)");assert("undefined"==typeof a.readBinary,"Module.readBinary option was removed (modify readBinary in JS)");
assert("undefined"==typeof a.setWindowTitle,"Module.setWindowTitle option was removed (modify setWindowTitle in JS)");assert("undefined"==typeof a.TOTAL_MEMORY,"Module.TOTAL_MEMORY has been renamed Module.INITIAL_MEMORY");Object.getOwnPropertyDescriptor(a,"read")||Object.defineProperty(a,"read",{configurable:!0,get:function(){k("Module.read has been replaced with plain read_ (the initial value can be provided on Module, but after startup the value is only looked for on a local variable of that name)")}});
Object.getOwnPropertyDescriptor(a,"readAsync")||Object.defineProperty(a,"readAsync",{configurable:!0,get:function(){k("Module.readAsync has been replaced with plain readAsync (the initial value can be provided on Module, but after startup the value is only looked for on a local variable of that name)")}});Object.getOwnPropertyDescriptor(a,"readBinary")||Object.defineProperty(a,"readBinary",{configurable:!0,get:function(){k("Module.readBinary has been replaced with plain readBinary (the initial value can be provided on Module, but after startup the value is only looked for on a local variable of that name)")}});
Object.getOwnPropertyDescriptor(a,"setWindowTitle")||Object.defineProperty(a,"setWindowTitle",{configurable:!0,get:function(){k("Module.setWindowTitle has been replaced with plain setWindowTitle (the initial value can be provided on Module, but after startup the value is only looked for on a local variable of that name)")}});assert(!r,"shell environment detected but not enabled at build time.  Add 'shell' to `-s ENVIRONMENT` to enable.");var A;a.wasmBinary&&(A=a.wasmBinary);
Object.getOwnPropertyDescriptor(a,"wasmBinary")||Object.defineProperty(a,"wasmBinary",{configurable:!0,get:function(){k("Module.wasmBinary has been replaced with plain wasmBinary (the initial value can be provided on Module, but after startup the value is only looked for on a local variable of that name)")}});var noExitRuntime=a.noExitRuntime||!0;Object.getOwnPropertyDescriptor(a,"noExitRuntime")||Object.defineProperty(a,"noExitRuntime",{configurable:!0,get:function(){k("Module.noExitRuntime has been replaced with plain noExitRuntime (the initial value can be provided on Module, but after startup the value is only looked for on a local variable of that name)")}});
"object"!=typeof WebAssembly&&k("no native wasm support detected");var C,D=!1;function assert(c,d){c||k("Assertion failed"+(d?": "+d:""))}"undefined"!=typeof TextDecoder&&new TextDecoder("utf8");"undefined"!=typeof TextDecoder&&new TextDecoder("utf-16le");var E,F,G,H;a.TOTAL_STACK&&assert(5242880===a.TOTAL_STACK,"the stack size can no longer be determined at runtime");var I=a.INITIAL_MEMORY||16777216;
Object.getOwnPropertyDescriptor(a,"INITIAL_MEMORY")||Object.defineProperty(a,"INITIAL_MEMORY",{configurable:!0,get:function(){k("Module.INITIAL_MEMORY has been replaced with plain INITIAL_MEMORY (the initial value can be provided on Module, but after startup the value is only looked for on a local variable of that name)")}});assert(5242880<=I,"INITIAL_MEMORY should be larger than TOTAL_STACK, was "+I+"! (TOTAL_STACK=5242880)");
assert("undefined"!=typeof Int32Array&&"undefined"!==typeof Float64Array&&void 0!=Int32Array.prototype.subarray&&void 0!=Int32Array.prototype.set,"JS engine does not provide full typed array support");assert(!a.wasmMemory,"Use of `wasmMemory` detected.  Use -s IMPORTED_MEMORY to define wasmMemory externally");assert(16777216==I,"Detected runtime INITIAL_MEMORY setting.  Use -s IMPORTED_MEMORY to define wasmMemory dynamically");var J;
function K(){var c=L();assert(0==(c&3));G[c+4>>2]=34821223;G[c+8>>2]=2310721022;G[0]=1668509029}function M(){if(!D){var c=L(),d=H[c+4>>2];c=H[c+8>>2];34821223==d&&2310721022==c||k("Stack overflow! Stack cookie has been overwritten, expected hex dwords 0x89BACDFE and 0x2135467, but received 0x"+c.toString(16)+" 0x"+d.toString(16));1668509029!==G[0]&&k("Runtime error: The application has corrupted its heap memory area (address zero)!")}}var N=new Int16Array(1),O=new Int8Array(N.buffer);N[0]=25459;
if(115!==O[0]||99!==O[1])throw"Runtime error: expected the system to be little-endian! (Run with -s SUPPORT_BIG_ENDIAN=1 to bypass)";var aa=[],ba=[],ca=[],P=!1;function da(){var c=a.preRun.shift();aa.unshift(c)}assert(Math.imul,"This browser does not support Math.imul(), build with LEGACY_VM_SUPPORT or POLYFILL_OLD_MATH_FUNCTIONS to add in a polyfill");assert(Math.fround,"This browser does not support Math.fround(), build with LEGACY_VM_SUPPORT or POLYFILL_OLD_MATH_FUNCTIONS to add in a polyfill");
assert(Math.clz32,"This browser does not support Math.clz32(), build with LEGACY_VM_SUPPORT or POLYFILL_OLD_MATH_FUNCTIONS to add in a polyfill");assert(Math.trunc,"This browser does not support Math.trunc(), build with LEGACY_VM_SUPPORT or POLYFILL_OLD_MATH_FUNCTIONS to add in a polyfill");var Q=0,R=null,S=null,T={};
function ea(){Q++;a.monitorRunDependencies&&a.monitorRunDependencies(Q);assert(!T["wasm-instantiate"]);T["wasm-instantiate"]=1;null===R&&"undefined"!=typeof setInterval&&(R=setInterval(function(){if(D)clearInterval(R),R=null;else{var c=!1,d;for(d in T)c||(c=!0,z("still waiting on run dependencies:")),z("dependency: "+d);c&&z("(end of list)")}},1E4))}a.preloadedImages={};a.preloadedAudios={};
function k(c){if(a.onAbort)a.onAbort(c);c="Aborted("+c+")";z(c);D=!0;c=new WebAssembly.RuntimeError(c);h(c);throw c;}function fa(){k("Filesystem support (FS) was not included. The problem is that you are using files from JS, but files were not used from C/C++, so filesystem support was not auto-included. You can force-include filesystem support with  -s FORCE_FILESYSTEM=1")}a.FS_createDataFile=function(){fa()};a.FS_createPreloadedFile=function(){fa()};
function ha(){return U.startsWith("data:application/octet-stream;base64,")}function V(c){return function(){var d=a.asm;assert(P,"native function `"+c+"` called before runtime initialization");assert(!0,"native function `"+c+"` called after runtime exit (use NO_EXIT_RUNTIME to keep it alive after main() exits)");d[c]||assert(d[c],"exported native function `"+c+"` not found");return d[c].apply(null,arguments)}}var U;
if(a.locateFile){if(U="wasm_interface.wasm",!ha()){var ia=U;U=a.locateFile?a.locateFile(ia,t):t+ia}}else U=(new URL("wasm_interface.wasm",import.meta.url)).toString();function ja(){var c=U;try{if(c==U&&A)return new Uint8Array(A);if(w)return w(c);throw"both async and sync fetching of the wasm failed";}catch(d){k(d)}}
function ka(){if(!A&&(m||n)){if("function"==typeof fetch&&!U.startsWith("file://"))return fetch(U,{credentials:"same-origin"}).then(function(c){if(!c.ok)throw"failed to load wasm binary file at '"+U+"'";return c.arrayBuffer()}).catch(function(){return ja()});if(v)return new Promise(function(c,d){v(U,function(e){c(new Uint8Array(e))},d)})}return Promise.resolve().then(function(){return ja()})}
function W(c){for(;0<c.length;){var d=c.shift();if("function"==typeof d)d(a);else{var e=d.u;"number"==typeof e?void 0===d.h?la(e)():la(e)(d.h):e(void 0===d.h?null:d.h)}}}var X=[];function la(c){var d=X[c];d||(c>=X.length&&(X.length=c+1),X[c]=d=J.get(c));assert(J.get(c)==d,"JavaScript-side Wasm function table mirror is out of date!");return d}
function ma(c){this.g=c-16;this.s=function(d){G[this.g+4>>2]=d};this.l=function(d){G[this.g+8>>2]=d};this.m=function(){G[this.g>>2]=0};this.j=function(){E[this.g+12>>0]=0};this.o=function(){E[this.g+13>>0]=0};this.i=function(d,e){this.s(d);this.l(e);this.m();this.j();this.o()}}
var na=0,pa={__cxa_allocate_exception:function(c){return oa(c+16)+16},__cxa_throw:function(c,d,e){(new ma(c)).i(d,e);na++;throw c+" - Exception catching is disabled, this exception cannot be caught. Compile with -s NO_DISABLE_EXCEPTION_CATCHING or -s EXCEPTION_CATCHING_ALLOWED=[..] to catch.";},abort:function(){k("native code called abort()")},emscripten_memcpy_big:function(c,d,e){F.copyWithin(c,d,d+e)},emscripten_resize_heap:function(c){k("Cannot enlarge memory arrays to size "+(c>>>0)+" bytes (OOM). Either (1) compile with  -s INITIAL_MEMORY=X  with X higher than the current value "+
E.length+", (2) compile with  -s ALLOW_MEMORY_GROWTH=1  which allows increasing the size at runtime, or (3) if you want malloc to return NULL (0) instead of this abort, compile with  -s ABORTING_MALLOC=0 ")}};
(function(){function c(f){a.asm=f.exports;C=a.asm.memory;assert(C,"memory not found in wasm exports");f=C.buffer;a.HEAP8=E=new Int8Array(f);a.HEAP16=new Int16Array(f);a.HEAP32=G=new Int32Array(f);a.HEAPU8=F=new Uint8Array(f);a.HEAPU16=new Uint16Array(f);a.HEAPU32=H=new Uint32Array(f);a.HEAPF32=new Float32Array(f);a.HEAPF64=new Float64Array(f);J=a.asm.__indirect_function_table;assert(J,"table not found in wasm exports");ba.unshift(a.asm.__wasm_call_ctors);Q--;a.monitorRunDependencies&&a.monitorRunDependencies(Q);
assert(T["wasm-instantiate"]);delete T["wasm-instantiate"];0==Q&&(null!==R&&(clearInterval(R),R=null),S&&(f=S,S=null,f()))}function d(f){assert(a===B,"the Module object should not be replaced during async compilation - perhaps the order of HTML elements is wrong?");B=null;c(f.instance)}function e(f){return ka().then(function(p){return WebAssembly.instantiate(p,g)}).then(function(p){return p}).then(f,function(p){z("failed to asynchronously prepare wasm: "+p);U.startsWith("file://")&&z("warning: Loading from a file URI ("+
U+") is not supported in most browsers. See https://emscripten.org/docs/getting_started/FAQ.html#how-do-i-run-a-local-webserver-for-testing-why-does-my-program-stall-in-downloading-or-preparing");k(p)})}var g={env:pa,wasi_snapshot_preview1:pa};ea();var B=a;if(a.instantiateWasm)try{return a.instantiateWasm(g,c)}catch(f){return z("Module.instantiateWasm callback failed with error: "+f),!1}(function(){return A||"function"!=typeof WebAssembly.instantiateStreaming||ha()||U.startsWith("file://")||"function"!=
typeof fetch?e(d):fetch(U,{credentials:"same-origin"}).then(function(f){return WebAssembly.instantiateStreaming(f,g).then(d,function(p){z("wasm streaming compile failed: "+p);z("falling back to ArrayBuffer instantiation");return e(d)})})})().catch(h);return{}})();a.___wasm_call_ctors=V("__wasm_call_ctors");a._get_pitch_mpm_c=V("get_pitch_mpm_c");a.___errno_location=V("__errno_location");a.___stdio_exit=V("__stdio_exit");var oa=a._malloc=V("malloc");a._free=V("free");
var qa=a._emscripten_stack_init=function(){return(qa=a._emscripten_stack_init=a.asm.emscripten_stack_init).apply(null,arguments)};a._emscripten_stack_get_free=function(){return(a._emscripten_stack_get_free=a.asm.emscripten_stack_get_free).apply(null,arguments)};a._emscripten_stack_get_base=function(){return(a._emscripten_stack_get_base=a.asm.emscripten_stack_get_base).apply(null,arguments)};
var L=a._emscripten_stack_get_end=function(){return(L=a._emscripten_stack_get_end=a.asm.emscripten_stack_get_end).apply(null,arguments)};a.stackSave=V("stackSave");a.stackRestore=V("stackRestore");a.stackAlloc=V("stackAlloc");Object.getOwnPropertyDescriptor(a,"intArrayFromString")||(a.intArrayFromString=()=>k("'intArrayFromString' was not exported. add it to EXPORTED_RUNTIME_METHODS (see the FAQ)"));Object.getOwnPropertyDescriptor(a,"intArrayToString")||(a.intArrayToString=()=>k("'intArrayToString' was not exported. add it to EXPORTED_RUNTIME_METHODS (see the FAQ)"));
Object.getOwnPropertyDescriptor(a,"ccall")||(a.ccall=()=>k("'ccall' was not exported. add it to EXPORTED_RUNTIME_METHODS (see the FAQ)"));Object.getOwnPropertyDescriptor(a,"cwrap")||(a.cwrap=()=>k("'cwrap' was not exported. add it to EXPORTED_RUNTIME_METHODS (see the FAQ)"));Object.getOwnPropertyDescriptor(a,"setValue")||(a.setValue=()=>k("'setValue' was not exported. add it to EXPORTED_RUNTIME_METHODS (see the FAQ)"));Object.getOwnPropertyDescriptor(a,"getValue")||(a.getValue=()=>k("'getValue' was not exported. add it to EXPORTED_RUNTIME_METHODS (see the FAQ)"));
Object.getOwnPropertyDescriptor(a,"allocate")||(a.allocate=()=>k("'allocate' was not exported. add it to EXPORTED_RUNTIME_METHODS (see the FAQ)"));Object.getOwnPropertyDescriptor(a,"UTF8ArrayToString")||(a.UTF8ArrayToString=()=>k("'UTF8ArrayToString' was not exported. add it to EXPORTED_RUNTIME_METHODS (see the FAQ)"));Object.getOwnPropertyDescriptor(a,"UTF8ToString")||(a.UTF8ToString=()=>k("'UTF8ToString' was not exported. add it to EXPORTED_RUNTIME_METHODS (see the FAQ)"));
Object.getOwnPropertyDescriptor(a,"stringToUTF8Array")||(a.stringToUTF8Array=()=>k("'stringToUTF8Array' was not exported. add it to EXPORTED_RUNTIME_METHODS (see the FAQ)"));Object.getOwnPropertyDescriptor(a,"stringToUTF8")||(a.stringToUTF8=()=>k("'stringToUTF8' was not exported. add it to EXPORTED_RUNTIME_METHODS (see the FAQ)"));Object.getOwnPropertyDescriptor(a,"lengthBytesUTF8")||(a.lengthBytesUTF8=()=>k("'lengthBytesUTF8' was not exported. add it to EXPORTED_RUNTIME_METHODS (see the FAQ)"));
Object.getOwnPropertyDescriptor(a,"stackTrace")||(a.stackTrace=()=>k("'stackTrace' was not exported. add it to EXPORTED_RUNTIME_METHODS (see the FAQ)"));Object.getOwnPropertyDescriptor(a,"addOnPreRun")||(a.addOnPreRun=()=>k("'addOnPreRun' was not exported. add it to EXPORTED_RUNTIME_METHODS (see the FAQ)"));Object.getOwnPropertyDescriptor(a,"addOnInit")||(a.addOnInit=()=>k("'addOnInit' was not exported. add it to EXPORTED_RUNTIME_METHODS (see the FAQ)"));
Object.getOwnPropertyDescriptor(a,"addOnPreMain")||(a.addOnPreMain=()=>k("'addOnPreMain' was not exported. add it to EXPORTED_RUNTIME_METHODS (see the FAQ)"));Object.getOwnPropertyDescriptor(a,"addOnExit")||(a.addOnExit=()=>k("'addOnExit' was not exported. add it to EXPORTED_RUNTIME_METHODS (see the FAQ)"));Object.getOwnPropertyDescriptor(a,"addOnPostRun")||(a.addOnPostRun=()=>k("'addOnPostRun' was not exported. add it to EXPORTED_RUNTIME_METHODS (see the FAQ)"));
Object.getOwnPropertyDescriptor(a,"writeStringToMemory")||(a.writeStringToMemory=()=>k("'writeStringToMemory' was not exported. add it to EXPORTED_RUNTIME_METHODS (see the FAQ)"));Object.getOwnPropertyDescriptor(a,"writeArrayToMemory")||(a.writeArrayToMemory=()=>k("'writeArrayToMemory' was not exported. add it to EXPORTED_RUNTIME_METHODS (see the FAQ)"));Object.getOwnPropertyDescriptor(a,"writeAsciiToMemory")||(a.writeAsciiToMemory=()=>k("'writeAsciiToMemory' was not exported. add it to EXPORTED_RUNTIME_METHODS (see the FAQ)"));
Object.getOwnPropertyDescriptor(a,"addRunDependency")||(a.addRunDependency=()=>k("'addRunDependency' was not exported. add it to EXPORTED_RUNTIME_METHODS (see the FAQ). Alternatively, forcing filesystem support (-s FORCE_FILESYSTEM=1) can export this for you"));Object.getOwnPropertyDescriptor(a,"removeRunDependency")||(a.removeRunDependency=()=>k("'removeRunDependency' was not exported. add it to EXPORTED_RUNTIME_METHODS (see the FAQ). Alternatively, forcing filesystem support (-s FORCE_FILESYSTEM=1) can export this for you"));
Object.getOwnPropertyDescriptor(a,"FS_createFolder")||(a.FS_createFolder=()=>k("'FS_createFolder' was not exported. add it to EXPORTED_RUNTIME_METHODS (see the FAQ)"));Object.getOwnPropertyDescriptor(a,"FS_createPath")||(a.FS_createPath=()=>k("'FS_createPath' was not exported. add it to EXPORTED_RUNTIME_METHODS (see the FAQ). Alternatively, forcing filesystem support (-s FORCE_FILESYSTEM=1) can export this for you"));
Object.getOwnPropertyDescriptor(a,"FS_createDataFile")||(a.FS_createDataFile=()=>k("'FS_createDataFile' was not exported. add it to EXPORTED_RUNTIME_METHODS (see the FAQ). Alternatively, forcing filesystem support (-s FORCE_FILESYSTEM=1) can export this for you"));Object.getOwnPropertyDescriptor(a,"FS_createPreloadedFile")||(a.FS_createPreloadedFile=()=>k("'FS_createPreloadedFile' was not exported. add it to EXPORTED_RUNTIME_METHODS (see the FAQ). Alternatively, forcing filesystem support (-s FORCE_FILESYSTEM=1) can export this for you"));
Object.getOwnPropertyDescriptor(a,"FS_createLazyFile")||(a.FS_createLazyFile=()=>k("'FS_createLazyFile' was not exported. add it to EXPORTED_RUNTIME_METHODS (see the FAQ). Alternatively, forcing filesystem support (-s FORCE_FILESYSTEM=1) can export this for you"));Object.getOwnPropertyDescriptor(a,"FS_createLink")||(a.FS_createLink=()=>k("'FS_createLink' was not exported. add it to EXPORTED_RUNTIME_METHODS (see the FAQ)"));
Object.getOwnPropertyDescriptor(a,"FS_createDevice")||(a.FS_createDevice=()=>k("'FS_createDevice' was not exported. add it to EXPORTED_RUNTIME_METHODS (see the FAQ). Alternatively, forcing filesystem support (-s FORCE_FILESYSTEM=1) can export this for you"));Object.getOwnPropertyDescriptor(a,"FS_unlink")||(a.FS_unlink=()=>k("'FS_unlink' was not exported. add it to EXPORTED_RUNTIME_METHODS (see the FAQ). Alternatively, forcing filesystem support (-s FORCE_FILESYSTEM=1) can export this for you"));
Object.getOwnPropertyDescriptor(a,"getLEB")||(a.getLEB=()=>k("'getLEB' was not exported. add it to EXPORTED_RUNTIME_METHODS (see the FAQ)"));Object.getOwnPropertyDescriptor(a,"getFunctionTables")||(a.getFunctionTables=()=>k("'getFunctionTables' was not exported. add it to EXPORTED_RUNTIME_METHODS (see the FAQ)"));Object.getOwnPropertyDescriptor(a,"alignFunctionTables")||(a.alignFunctionTables=()=>k("'alignFunctionTables' was not exported. add it to EXPORTED_RUNTIME_METHODS (see the FAQ)"));
Object.getOwnPropertyDescriptor(a,"registerFunctions")||(a.registerFunctions=()=>k("'registerFunctions' was not exported. add it to EXPORTED_RUNTIME_METHODS (see the FAQ)"));Object.getOwnPropertyDescriptor(a,"addFunction")||(a.addFunction=()=>k("'addFunction' was not exported. add it to EXPORTED_RUNTIME_METHODS (see the FAQ)"));Object.getOwnPropertyDescriptor(a,"removeFunction")||(a.removeFunction=()=>k("'removeFunction' was not exported. add it to EXPORTED_RUNTIME_METHODS (see the FAQ)"));
Object.getOwnPropertyDescriptor(a,"getFuncWrapper")||(a.getFuncWrapper=()=>k("'getFuncWrapper' was not exported. add it to EXPORTED_RUNTIME_METHODS (see the FAQ)"));Object.getOwnPropertyDescriptor(a,"prettyPrint")||(a.prettyPrint=()=>k("'prettyPrint' was not exported. add it to EXPORTED_RUNTIME_METHODS (see the FAQ)"));Object.getOwnPropertyDescriptor(a,"dynCall")||(a.dynCall=()=>k("'dynCall' was not exported. add it to EXPORTED_RUNTIME_METHODS (see the FAQ)"));
Object.getOwnPropertyDescriptor(a,"getCompilerSetting")||(a.getCompilerSetting=()=>k("'getCompilerSetting' was not exported. add it to EXPORTED_RUNTIME_METHODS (see the FAQ)"));Object.getOwnPropertyDescriptor(a,"print")||(a.print=()=>k("'print' was not exported. add it to EXPORTED_RUNTIME_METHODS (see the FAQ)"));Object.getOwnPropertyDescriptor(a,"printErr")||(a.printErr=()=>k("'printErr' was not exported. add it to EXPORTED_RUNTIME_METHODS (see the FAQ)"));
Object.getOwnPropertyDescriptor(a,"getTempRet0")||(a.getTempRet0=()=>k("'getTempRet0' was not exported. add it to EXPORTED_RUNTIME_METHODS (see the FAQ)"));Object.getOwnPropertyDescriptor(a,"setTempRet0")||(a.setTempRet0=()=>k("'setTempRet0' was not exported. add it to EXPORTED_RUNTIME_METHODS (see the FAQ)"));Object.getOwnPropertyDescriptor(a,"callMain")||(a.callMain=()=>k("'callMain' was not exported. add it to EXPORTED_RUNTIME_METHODS (see the FAQ)"));
Object.getOwnPropertyDescriptor(a,"abort")||(a.abort=()=>k("'abort' was not exported. add it to EXPORTED_RUNTIME_METHODS (see the FAQ)"));Object.getOwnPropertyDescriptor(a,"keepRuntimeAlive")||(a.keepRuntimeAlive=()=>k("'keepRuntimeAlive' was not exported. add it to EXPORTED_RUNTIME_METHODS (see the FAQ)"));Object.getOwnPropertyDescriptor(a,"zeroMemory")||(a.zeroMemory=()=>k("'zeroMemory' was not exported. add it to EXPORTED_RUNTIME_METHODS (see the FAQ)"));
Object.getOwnPropertyDescriptor(a,"stringToNewUTF8")||(a.stringToNewUTF8=()=>k("'stringToNewUTF8' was not exported. add it to EXPORTED_RUNTIME_METHODS (see the FAQ)"));Object.getOwnPropertyDescriptor(a,"abortOnCannotGrowMemory")||(a.abortOnCannotGrowMemory=()=>k("'abortOnCannotGrowMemory' was not exported. add it to EXPORTED_RUNTIME_METHODS (see the FAQ)"));Object.getOwnPropertyDescriptor(a,"emscripten_realloc_buffer")||(a.emscripten_realloc_buffer=()=>k("'emscripten_realloc_buffer' was not exported. add it to EXPORTED_RUNTIME_METHODS (see the FAQ)"));
Object.getOwnPropertyDescriptor(a,"ENV")||(a.ENV=()=>k("'ENV' was not exported. add it to EXPORTED_RUNTIME_METHODS (see the FAQ)"));Object.getOwnPropertyDescriptor(a,"withStackSave")||(a.withStackSave=()=>k("'withStackSave' was not exported. add it to EXPORTED_RUNTIME_METHODS (see the FAQ)"));Object.getOwnPropertyDescriptor(a,"ERRNO_CODES")||(a.ERRNO_CODES=()=>k("'ERRNO_CODES' was not exported. add it to EXPORTED_RUNTIME_METHODS (see the FAQ)"));
Object.getOwnPropertyDescriptor(a,"ERRNO_MESSAGES")||(a.ERRNO_MESSAGES=()=>k("'ERRNO_MESSAGES' was not exported. add it to EXPORTED_RUNTIME_METHODS (see the FAQ)"));Object.getOwnPropertyDescriptor(a,"setErrNo")||(a.setErrNo=()=>k("'setErrNo' was not exported. add it to EXPORTED_RUNTIME_METHODS (see the FAQ)"));Object.getOwnPropertyDescriptor(a,"inetPton4")||(a.inetPton4=()=>k("'inetPton4' was not exported. add it to EXPORTED_RUNTIME_METHODS (see the FAQ)"));
Object.getOwnPropertyDescriptor(a,"inetNtop4")||(a.inetNtop4=()=>k("'inetNtop4' was not exported. add it to EXPORTED_RUNTIME_METHODS (see the FAQ)"));Object.getOwnPropertyDescriptor(a,"inetPton6")||(a.inetPton6=()=>k("'inetPton6' was not exported. add it to EXPORTED_RUNTIME_METHODS (see the FAQ)"));Object.getOwnPropertyDescriptor(a,"inetNtop6")||(a.inetNtop6=()=>k("'inetNtop6' was not exported. add it to EXPORTED_RUNTIME_METHODS (see the FAQ)"));
Object.getOwnPropertyDescriptor(a,"readSockaddr")||(a.readSockaddr=()=>k("'readSockaddr' was not exported. add it to EXPORTED_RUNTIME_METHODS (see the FAQ)"));Object.getOwnPropertyDescriptor(a,"writeSockaddr")||(a.writeSockaddr=()=>k("'writeSockaddr' was not exported. add it to EXPORTED_RUNTIME_METHODS (see the FAQ)"));Object.getOwnPropertyDescriptor(a,"DNS")||(a.DNS=()=>k("'DNS' was not exported. add it to EXPORTED_RUNTIME_METHODS (see the FAQ)"));
Object.getOwnPropertyDescriptor(a,"getHostByName")||(a.getHostByName=()=>k("'getHostByName' was not exported. add it to EXPORTED_RUNTIME_METHODS (see the FAQ)"));Object.getOwnPropertyDescriptor(a,"Protocols")||(a.Protocols=()=>k("'Protocols' was not exported. add it to EXPORTED_RUNTIME_METHODS (see the FAQ)"));Object.getOwnPropertyDescriptor(a,"Sockets")||(a.Sockets=()=>k("'Sockets' was not exported. add it to EXPORTED_RUNTIME_METHODS (see the FAQ)"));
Object.getOwnPropertyDescriptor(a,"getRandomDevice")||(a.getRandomDevice=()=>k("'getRandomDevice' was not exported. add it to EXPORTED_RUNTIME_METHODS (see the FAQ)"));Object.getOwnPropertyDescriptor(a,"traverseStack")||(a.traverseStack=()=>k("'traverseStack' was not exported. add it to EXPORTED_RUNTIME_METHODS (see the FAQ)"));Object.getOwnPropertyDescriptor(a,"convertFrameToPC")||(a.convertFrameToPC=()=>k("'convertFrameToPC' was not exported. add it to EXPORTED_RUNTIME_METHODS (see the FAQ)"));
Object.getOwnPropertyDescriptor(a,"UNWIND_CACHE")||(a.UNWIND_CACHE=()=>k("'UNWIND_CACHE' was not exported. add it to EXPORTED_RUNTIME_METHODS (see the FAQ)"));Object.getOwnPropertyDescriptor(a,"saveInUnwindCache")||(a.saveInUnwindCache=()=>k("'saveInUnwindCache' was not exported. add it to EXPORTED_RUNTIME_METHODS (see the FAQ)"));Object.getOwnPropertyDescriptor(a,"convertPCtoSourceLocation")||(a.convertPCtoSourceLocation=()=>k("'convertPCtoSourceLocation' was not exported. add it to EXPORTED_RUNTIME_METHODS (see the FAQ)"));
Object.getOwnPropertyDescriptor(a,"readAsmConstArgsArray")||(a.readAsmConstArgsArray=()=>k("'readAsmConstArgsArray' was not exported. add it to EXPORTED_RUNTIME_METHODS (see the FAQ)"));Object.getOwnPropertyDescriptor(a,"readAsmConstArgs")||(a.readAsmConstArgs=()=>k("'readAsmConstArgs' was not exported. add it to EXPORTED_RUNTIME_METHODS (see the FAQ)"));Object.getOwnPropertyDescriptor(a,"mainThreadEM_ASM")||(a.mainThreadEM_ASM=()=>k("'mainThreadEM_ASM' was not exported. add it to EXPORTED_RUNTIME_METHODS (see the FAQ)"));
Object.getOwnPropertyDescriptor(a,"jstoi_q")||(a.jstoi_q=()=>k("'jstoi_q' was not exported. add it to EXPORTED_RUNTIME_METHODS (see the FAQ)"));Object.getOwnPropertyDescriptor(a,"jstoi_s")||(a.jstoi_s=()=>k("'jstoi_s' was not exported. add it to EXPORTED_RUNTIME_METHODS (see the FAQ)"));Object.getOwnPropertyDescriptor(a,"getExecutableName")||(a.getExecutableName=()=>k("'getExecutableName' was not exported. add it to EXPORTED_RUNTIME_METHODS (see the FAQ)"));
Object.getOwnPropertyDescriptor(a,"listenOnce")||(a.listenOnce=()=>k("'listenOnce' was not exported. add it to EXPORTED_RUNTIME_METHODS (see the FAQ)"));Object.getOwnPropertyDescriptor(a,"autoResumeAudioContext")||(a.autoResumeAudioContext=()=>k("'autoResumeAudioContext' was not exported. add it to EXPORTED_RUNTIME_METHODS (see the FAQ)"));Object.getOwnPropertyDescriptor(a,"dynCallLegacy")||(a.dynCallLegacy=()=>k("'dynCallLegacy' was not exported. add it to EXPORTED_RUNTIME_METHODS (see the FAQ)"));
Object.getOwnPropertyDescriptor(a,"getDynCaller")||(a.getDynCaller=()=>k("'getDynCaller' was not exported. add it to EXPORTED_RUNTIME_METHODS (see the FAQ)"));Object.getOwnPropertyDescriptor(a,"dynCall")||(a.dynCall=()=>k("'dynCall' was not exported. add it to EXPORTED_RUNTIME_METHODS (see the FAQ)"));Object.getOwnPropertyDescriptor(a,"callRuntimeCallbacks")||(a.callRuntimeCallbacks=()=>k("'callRuntimeCallbacks' was not exported. add it to EXPORTED_RUNTIME_METHODS (see the FAQ)"));
Object.getOwnPropertyDescriptor(a,"wasmTableMirror")||(a.wasmTableMirror=()=>k("'wasmTableMirror' was not exported. add it to EXPORTED_RUNTIME_METHODS (see the FAQ)"));Object.getOwnPropertyDescriptor(a,"setWasmTableEntry")||(a.setWasmTableEntry=()=>k("'setWasmTableEntry' was not exported. add it to EXPORTED_RUNTIME_METHODS (see the FAQ)"));Object.getOwnPropertyDescriptor(a,"getWasmTableEntry")||(a.getWasmTableEntry=()=>k("'getWasmTableEntry' was not exported. add it to EXPORTED_RUNTIME_METHODS (see the FAQ)"));
Object.getOwnPropertyDescriptor(a,"handleException")||(a.handleException=()=>k("'handleException' was not exported. add it to EXPORTED_RUNTIME_METHODS (see the FAQ)"));Object.getOwnPropertyDescriptor(a,"runtimeKeepalivePush")||(a.runtimeKeepalivePush=()=>k("'runtimeKeepalivePush' was not exported. add it to EXPORTED_RUNTIME_METHODS (see the FAQ)"));Object.getOwnPropertyDescriptor(a,"runtimeKeepalivePop")||(a.runtimeKeepalivePop=()=>k("'runtimeKeepalivePop' was not exported. add it to EXPORTED_RUNTIME_METHODS (see the FAQ)"));
Object.getOwnPropertyDescriptor(a,"callUserCallback")||(a.callUserCallback=()=>k("'callUserCallback' was not exported. add it to EXPORTED_RUNTIME_METHODS (see the FAQ)"));Object.getOwnPropertyDescriptor(a,"maybeExit")||(a.maybeExit=()=>k("'maybeExit' was not exported. add it to EXPORTED_RUNTIME_METHODS (see the FAQ)"));Object.getOwnPropertyDescriptor(a,"safeSetTimeout")||(a.safeSetTimeout=()=>k("'safeSetTimeout' was not exported. add it to EXPORTED_RUNTIME_METHODS (see the FAQ)"));
Object.getOwnPropertyDescriptor(a,"asmjsMangle")||(a.asmjsMangle=()=>k("'asmjsMangle' was not exported. add it to EXPORTED_RUNTIME_METHODS (see the FAQ)"));Object.getOwnPropertyDescriptor(a,"asyncLoad")||(a.asyncLoad=()=>k("'asyncLoad' was not exported. add it to EXPORTED_RUNTIME_METHODS (see the FAQ)"));Object.getOwnPropertyDescriptor(a,"alignMemory")||(a.alignMemory=()=>k("'alignMemory' was not exported. add it to EXPORTED_RUNTIME_METHODS (see the FAQ)"));
Object.getOwnPropertyDescriptor(a,"mmapAlloc")||(a.mmapAlloc=()=>k("'mmapAlloc' was not exported. add it to EXPORTED_RUNTIME_METHODS (see the FAQ)"));Object.getOwnPropertyDescriptor(a,"reallyNegative")||(a.reallyNegative=()=>k("'reallyNegative' was not exported. add it to EXPORTED_RUNTIME_METHODS (see the FAQ)"));Object.getOwnPropertyDescriptor(a,"unSign")||(a.unSign=()=>k("'unSign' was not exported. add it to EXPORTED_RUNTIME_METHODS (see the FAQ)"));
Object.getOwnPropertyDescriptor(a,"reSign")||(a.reSign=()=>k("'reSign' was not exported. add it to EXPORTED_RUNTIME_METHODS (see the FAQ)"));Object.getOwnPropertyDescriptor(a,"formatString")||(a.formatString=()=>k("'formatString' was not exported. add it to EXPORTED_RUNTIME_METHODS (see the FAQ)"));Object.getOwnPropertyDescriptor(a,"PATH")||(a.PATH=()=>k("'PATH' was not exported. add it to EXPORTED_RUNTIME_METHODS (see the FAQ)"));Object.getOwnPropertyDescriptor(a,"PATH_FS")||(a.PATH_FS=()=>k("'PATH_FS' was not exported. add it to EXPORTED_RUNTIME_METHODS (see the FAQ)"));
Object.getOwnPropertyDescriptor(a,"SYSCALLS")||(a.SYSCALLS=()=>k("'SYSCALLS' was not exported. add it to EXPORTED_RUNTIME_METHODS (see the FAQ)"));Object.getOwnPropertyDescriptor(a,"getSocketFromFD")||(a.getSocketFromFD=()=>k("'getSocketFromFD' was not exported. add it to EXPORTED_RUNTIME_METHODS (see the FAQ)"));Object.getOwnPropertyDescriptor(a,"getSocketAddress")||(a.getSocketAddress=()=>k("'getSocketAddress' was not exported. add it to EXPORTED_RUNTIME_METHODS (see the FAQ)"));
Object.getOwnPropertyDescriptor(a,"JSEvents")||(a.JSEvents=()=>k("'JSEvents' was not exported. add it to EXPORTED_RUNTIME_METHODS (see the FAQ)"));Object.getOwnPropertyDescriptor(a,"registerKeyEventCallback")||(a.registerKeyEventCallback=()=>k("'registerKeyEventCallback' was not exported. add it to EXPORTED_RUNTIME_METHODS (see the FAQ)"));Object.getOwnPropertyDescriptor(a,"specialHTMLTargets")||(a.specialHTMLTargets=()=>k("'specialHTMLTargets' was not exported. add it to EXPORTED_RUNTIME_METHODS (see the FAQ)"));
Object.getOwnPropertyDescriptor(a,"maybeCStringToJsString")||(a.maybeCStringToJsString=()=>k("'maybeCStringToJsString' was not exported. add it to EXPORTED_RUNTIME_METHODS (see the FAQ)"));Object.getOwnPropertyDescriptor(a,"findEventTarget")||(a.findEventTarget=()=>k("'findEventTarget' was not exported. add it to EXPORTED_RUNTIME_METHODS (see the FAQ)"));Object.getOwnPropertyDescriptor(a,"findCanvasEventTarget")||(a.findCanvasEventTarget=()=>k("'findCanvasEventTarget' was not exported. add it to EXPORTED_RUNTIME_METHODS (see the FAQ)"));
Object.getOwnPropertyDescriptor(a,"getBoundingClientRect")||(a.getBoundingClientRect=()=>k("'getBoundingClientRect' was not exported. add it to EXPORTED_RUNTIME_METHODS (see the FAQ)"));Object.getOwnPropertyDescriptor(a,"fillMouseEventData")||(a.fillMouseEventData=()=>k("'fillMouseEventData' was not exported. add it to EXPORTED_RUNTIME_METHODS (see the FAQ)"));Object.getOwnPropertyDescriptor(a,"registerMouseEventCallback")||(a.registerMouseEventCallback=()=>k("'registerMouseEventCallback' was not exported. add it to EXPORTED_RUNTIME_METHODS (see the FAQ)"));
Object.getOwnPropertyDescriptor(a,"registerWheelEventCallback")||(a.registerWheelEventCallback=()=>k("'registerWheelEventCallback' was not exported. add it to EXPORTED_RUNTIME_METHODS (see the FAQ)"));Object.getOwnPropertyDescriptor(a,"registerUiEventCallback")||(a.registerUiEventCallback=()=>k("'registerUiEventCallback' was not exported. add it to EXPORTED_RUNTIME_METHODS (see the FAQ)"));Object.getOwnPropertyDescriptor(a,"registerFocusEventCallback")||(a.registerFocusEventCallback=()=>k("'registerFocusEventCallback' was not exported. add it to EXPORTED_RUNTIME_METHODS (see the FAQ)"));
Object.getOwnPropertyDescriptor(a,"fillDeviceOrientationEventData")||(a.fillDeviceOrientationEventData=()=>k("'fillDeviceOrientationEventData' was not exported. add it to EXPORTED_RUNTIME_METHODS (see the FAQ)"));Object.getOwnPropertyDescriptor(a,"registerDeviceOrientationEventCallback")||(a.registerDeviceOrientationEventCallback=()=>k("'registerDeviceOrientationEventCallback' was not exported. add it to EXPORTED_RUNTIME_METHODS (see the FAQ)"));
Object.getOwnPropertyDescriptor(a,"fillDeviceMotionEventData")||(a.fillDeviceMotionEventData=()=>k("'fillDeviceMotionEventData' was not exported. add it to EXPORTED_RUNTIME_METHODS (see the FAQ)"));Object.getOwnPropertyDescriptor(a,"registerDeviceMotionEventCallback")||(a.registerDeviceMotionEventCallback=()=>k("'registerDeviceMotionEventCallback' was not exported. add it to EXPORTED_RUNTIME_METHODS (see the FAQ)"));
Object.getOwnPropertyDescriptor(a,"screenOrientation")||(a.screenOrientation=()=>k("'screenOrientation' was not exported. add it to EXPORTED_RUNTIME_METHODS (see the FAQ)"));Object.getOwnPropertyDescriptor(a,"fillOrientationChangeEventData")||(a.fillOrientationChangeEventData=()=>k("'fillOrientationChangeEventData' was not exported. add it to EXPORTED_RUNTIME_METHODS (see the FAQ)"));
Object.getOwnPropertyDescriptor(a,"registerOrientationChangeEventCallback")||(a.registerOrientationChangeEventCallback=()=>k("'registerOrientationChangeEventCallback' was not exported. add it to EXPORTED_RUNTIME_METHODS (see the FAQ)"));Object.getOwnPropertyDescriptor(a,"fillFullscreenChangeEventData")||(a.fillFullscreenChangeEventData=()=>k("'fillFullscreenChangeEventData' was not exported. add it to EXPORTED_RUNTIME_METHODS (see the FAQ)"));
Object.getOwnPropertyDescriptor(a,"registerFullscreenChangeEventCallback")||(a.registerFullscreenChangeEventCallback=()=>k("'registerFullscreenChangeEventCallback' was not exported. add it to EXPORTED_RUNTIME_METHODS (see the FAQ)"));Object.getOwnPropertyDescriptor(a,"registerRestoreOldStyle")||(a.registerRestoreOldStyle=()=>k("'registerRestoreOldStyle' was not exported. add it to EXPORTED_RUNTIME_METHODS (see the FAQ)"));
Object.getOwnPropertyDescriptor(a,"hideEverythingExceptGivenElement")||(a.hideEverythingExceptGivenElement=()=>k("'hideEverythingExceptGivenElement' was not exported. add it to EXPORTED_RUNTIME_METHODS (see the FAQ)"));Object.getOwnPropertyDescriptor(a,"restoreHiddenElements")||(a.restoreHiddenElements=()=>k("'restoreHiddenElements' was not exported. add it to EXPORTED_RUNTIME_METHODS (see the FAQ)"));Object.getOwnPropertyDescriptor(a,"setLetterbox")||(a.setLetterbox=()=>k("'setLetterbox' was not exported. add it to EXPORTED_RUNTIME_METHODS (see the FAQ)"));
Object.getOwnPropertyDescriptor(a,"currentFullscreenStrategy")||(a.currentFullscreenStrategy=()=>k("'currentFullscreenStrategy' was not exported. add it to EXPORTED_RUNTIME_METHODS (see the FAQ)"));Object.getOwnPropertyDescriptor(a,"restoreOldWindowedStyle")||(a.restoreOldWindowedStyle=()=>k("'restoreOldWindowedStyle' was not exported. add it to EXPORTED_RUNTIME_METHODS (see the FAQ)"));
Object.getOwnPropertyDescriptor(a,"softFullscreenResizeWebGLRenderTarget")||(a.softFullscreenResizeWebGLRenderTarget=()=>k("'softFullscreenResizeWebGLRenderTarget' was not exported. add it to EXPORTED_RUNTIME_METHODS (see the FAQ)"));Object.getOwnPropertyDescriptor(a,"doRequestFullscreen")||(a.doRequestFullscreen=()=>k("'doRequestFullscreen' was not exported. add it to EXPORTED_RUNTIME_METHODS (see the FAQ)"));
Object.getOwnPropertyDescriptor(a,"fillPointerlockChangeEventData")||(a.fillPointerlockChangeEventData=()=>k("'fillPointerlockChangeEventData' was not exported. add it to EXPORTED_RUNTIME_METHODS (see the FAQ)"));Object.getOwnPropertyDescriptor(a,"registerPointerlockChangeEventCallback")||(a.registerPointerlockChangeEventCallback=()=>k("'registerPointerlockChangeEventCallback' was not exported. add it to EXPORTED_RUNTIME_METHODS (see the FAQ)"));
Object.getOwnPropertyDescriptor(a,"registerPointerlockErrorEventCallback")||(a.registerPointerlockErrorEventCallback=()=>k("'registerPointerlockErrorEventCallback' was not exported. add it to EXPORTED_RUNTIME_METHODS (see the FAQ)"));Object.getOwnPropertyDescriptor(a,"requestPointerLock")||(a.requestPointerLock=()=>k("'requestPointerLock' was not exported. add it to EXPORTED_RUNTIME_METHODS (see the FAQ)"));
Object.getOwnPropertyDescriptor(a,"fillVisibilityChangeEventData")||(a.fillVisibilityChangeEventData=()=>k("'fillVisibilityChangeEventData' was not exported. add it to EXPORTED_RUNTIME_METHODS (see the FAQ)"));Object.getOwnPropertyDescriptor(a,"registerVisibilityChangeEventCallback")||(a.registerVisibilityChangeEventCallback=()=>k("'registerVisibilityChangeEventCallback' was not exported. add it to EXPORTED_RUNTIME_METHODS (see the FAQ)"));
Object.getOwnPropertyDescriptor(a,"registerTouchEventCallback")||(a.registerTouchEventCallback=()=>k("'registerTouchEventCallback' was not exported. add it to EXPORTED_RUNTIME_METHODS (see the FAQ)"));Object.getOwnPropertyDescriptor(a,"fillGamepadEventData")||(a.fillGamepadEventData=()=>k("'fillGamepadEventData' was not exported. add it to EXPORTED_RUNTIME_METHODS (see the FAQ)"));Object.getOwnPropertyDescriptor(a,"registerGamepadEventCallback")||(a.registerGamepadEventCallback=()=>k("'registerGamepadEventCallback' was not exported. add it to EXPORTED_RUNTIME_METHODS (see the FAQ)"));
Object.getOwnPropertyDescriptor(a,"registerBeforeUnloadEventCallback")||(a.registerBeforeUnloadEventCallback=()=>k("'registerBeforeUnloadEventCallback' was not exported. add it to EXPORTED_RUNTIME_METHODS (see the FAQ)"));Object.getOwnPropertyDescriptor(a,"fillBatteryEventData")||(a.fillBatteryEventData=()=>k("'fillBatteryEventData' was not exported. add it to EXPORTED_RUNTIME_METHODS (see the FAQ)"));Object.getOwnPropertyDescriptor(a,"battery")||(a.battery=()=>k("'battery' was not exported. add it to EXPORTED_RUNTIME_METHODS (see the FAQ)"));
Object.getOwnPropertyDescriptor(a,"registerBatteryEventCallback")||(a.registerBatteryEventCallback=()=>k("'registerBatteryEventCallback' was not exported. add it to EXPORTED_RUNTIME_METHODS (see the FAQ)"));Object.getOwnPropertyDescriptor(a,"setCanvasElementSize")||(a.setCanvasElementSize=()=>k("'setCanvasElementSize' was not exported. add it to EXPORTED_RUNTIME_METHODS (see the FAQ)"));Object.getOwnPropertyDescriptor(a,"getCanvasElementSize")||(a.getCanvasElementSize=()=>k("'getCanvasElementSize' was not exported. add it to EXPORTED_RUNTIME_METHODS (see the FAQ)"));
Object.getOwnPropertyDescriptor(a,"demangle")||(a.demangle=()=>k("'demangle' was not exported. add it to EXPORTED_RUNTIME_METHODS (see the FAQ)"));Object.getOwnPropertyDescriptor(a,"demangleAll")||(a.demangleAll=()=>k("'demangleAll' was not exported. add it to EXPORTED_RUNTIME_METHODS (see the FAQ)"));Object.getOwnPropertyDescriptor(a,"jsStackTrace")||(a.jsStackTrace=()=>k("'jsStackTrace' was not exported. add it to EXPORTED_RUNTIME_METHODS (see the FAQ)"));
Object.getOwnPropertyDescriptor(a,"stackTrace")||(a.stackTrace=()=>k("'stackTrace' was not exported. add it to EXPORTED_RUNTIME_METHODS (see the FAQ)"));Object.getOwnPropertyDescriptor(a,"getEnvStrings")||(a.getEnvStrings=()=>k("'getEnvStrings' was not exported. add it to EXPORTED_RUNTIME_METHODS (see the FAQ)"));Object.getOwnPropertyDescriptor(a,"checkWasiClock")||(a.checkWasiClock=()=>k("'checkWasiClock' was not exported. add it to EXPORTED_RUNTIME_METHODS (see the FAQ)"));
Object.getOwnPropertyDescriptor(a,"flush_NO_FILESYSTEM")||(a.flush_NO_FILESYSTEM=()=>k("'flush_NO_FILESYSTEM' was not exported. add it to EXPORTED_RUNTIME_METHODS (see the FAQ)"));Object.getOwnPropertyDescriptor(a,"writeI53ToI64")||(a.writeI53ToI64=()=>k("'writeI53ToI64' was not exported. add it to EXPORTED_RUNTIME_METHODS (see the FAQ)"));Object.getOwnPropertyDescriptor(a,"writeI53ToI64Clamped")||(a.writeI53ToI64Clamped=()=>k("'writeI53ToI64Clamped' was not exported. add it to EXPORTED_RUNTIME_METHODS (see the FAQ)"));
Object.getOwnPropertyDescriptor(a,"writeI53ToI64Signaling")||(a.writeI53ToI64Signaling=()=>k("'writeI53ToI64Signaling' was not exported. add it to EXPORTED_RUNTIME_METHODS (see the FAQ)"));Object.getOwnPropertyDescriptor(a,"writeI53ToU64Clamped")||(a.writeI53ToU64Clamped=()=>k("'writeI53ToU64Clamped' was not exported. add it to EXPORTED_RUNTIME_METHODS (see the FAQ)"));Object.getOwnPropertyDescriptor(a,"writeI53ToU64Signaling")||(a.writeI53ToU64Signaling=()=>k("'writeI53ToU64Signaling' was not exported. add it to EXPORTED_RUNTIME_METHODS (see the FAQ)"));
Object.getOwnPropertyDescriptor(a,"readI53FromI64")||(a.readI53FromI64=()=>k("'readI53FromI64' was not exported. add it to EXPORTED_RUNTIME_METHODS (see the FAQ)"));Object.getOwnPropertyDescriptor(a,"readI53FromU64")||(a.readI53FromU64=()=>k("'readI53FromU64' was not exported. add it to EXPORTED_RUNTIME_METHODS (see the FAQ)"));Object.getOwnPropertyDescriptor(a,"convertI32PairToI53")||(a.convertI32PairToI53=()=>k("'convertI32PairToI53' was not exported. add it to EXPORTED_RUNTIME_METHODS (see the FAQ)"));
Object.getOwnPropertyDescriptor(a,"convertU32PairToI53")||(a.convertU32PairToI53=()=>k("'convertU32PairToI53' was not exported. add it to EXPORTED_RUNTIME_METHODS (see the FAQ)"));Object.getOwnPropertyDescriptor(a,"setImmediateWrapped")||(a.setImmediateWrapped=()=>k("'setImmediateWrapped' was not exported. add it to EXPORTED_RUNTIME_METHODS (see the FAQ)"));Object.getOwnPropertyDescriptor(a,"clearImmediateWrapped")||(a.clearImmediateWrapped=()=>k("'clearImmediateWrapped' was not exported. add it to EXPORTED_RUNTIME_METHODS (see the FAQ)"));
Object.getOwnPropertyDescriptor(a,"polyfillSetImmediate")||(a.polyfillSetImmediate=()=>k("'polyfillSetImmediate' was not exported. add it to EXPORTED_RUNTIME_METHODS (see the FAQ)"));Object.getOwnPropertyDescriptor(a,"uncaughtExceptionCount")||(a.uncaughtExceptionCount=()=>k("'uncaughtExceptionCount' was not exported. add it to EXPORTED_RUNTIME_METHODS (see the FAQ)"));Object.getOwnPropertyDescriptor(a,"exceptionLast")||(a.exceptionLast=()=>k("'exceptionLast' was not exported. add it to EXPORTED_RUNTIME_METHODS (see the FAQ)"));
Object.getOwnPropertyDescriptor(a,"exceptionCaught")||(a.exceptionCaught=()=>k("'exceptionCaught' was not exported. add it to EXPORTED_RUNTIME_METHODS (see the FAQ)"));Object.getOwnPropertyDescriptor(a,"ExceptionInfo")||(a.ExceptionInfo=()=>k("'ExceptionInfo' was not exported. add it to EXPORTED_RUNTIME_METHODS (see the FAQ)"));Object.getOwnPropertyDescriptor(a,"CatchInfo")||(a.CatchInfo=()=>k("'CatchInfo' was not exported. add it to EXPORTED_RUNTIME_METHODS (see the FAQ)"));
Object.getOwnPropertyDescriptor(a,"exception_addRef")||(a.exception_addRef=()=>k("'exception_addRef' was not exported. add it to EXPORTED_RUNTIME_METHODS (see the FAQ)"));Object.getOwnPropertyDescriptor(a,"exception_decRef")||(a.exception_decRef=()=>k("'exception_decRef' was not exported. add it to EXPORTED_RUNTIME_METHODS (see the FAQ)"));Object.getOwnPropertyDescriptor(a,"Browser")||(a.Browser=()=>k("'Browser' was not exported. add it to EXPORTED_RUNTIME_METHODS (see the FAQ)"));
Object.getOwnPropertyDescriptor(a,"funcWrappers")||(a.funcWrappers=()=>k("'funcWrappers' was not exported. add it to EXPORTED_RUNTIME_METHODS (see the FAQ)"));Object.getOwnPropertyDescriptor(a,"getFuncWrapper")||(a.getFuncWrapper=()=>k("'getFuncWrapper' was not exported. add it to EXPORTED_RUNTIME_METHODS (see the FAQ)"));Object.getOwnPropertyDescriptor(a,"setMainLoop")||(a.setMainLoop=()=>k("'setMainLoop' was not exported. add it to EXPORTED_RUNTIME_METHODS (see the FAQ)"));
Object.getOwnPropertyDescriptor(a,"wget")||(a.wget=()=>k("'wget' was not exported. add it to EXPORTED_RUNTIME_METHODS (see the FAQ)"));Object.getOwnPropertyDescriptor(a,"tempFixedLengthArray")||(a.tempFixedLengthArray=()=>k("'tempFixedLengthArray' was not exported. add it to EXPORTED_RUNTIME_METHODS (see the FAQ)"));Object.getOwnPropertyDescriptor(a,"miniTempWebGLFloatBuffers")||(a.miniTempWebGLFloatBuffers=()=>k("'miniTempWebGLFloatBuffers' was not exported. add it to EXPORTED_RUNTIME_METHODS (see the FAQ)"));
Object.getOwnPropertyDescriptor(a,"heapObjectForWebGLType")||(a.heapObjectForWebGLType=()=>k("'heapObjectForWebGLType' was not exported. add it to EXPORTED_RUNTIME_METHODS (see the FAQ)"));Object.getOwnPropertyDescriptor(a,"heapAccessShiftForWebGLHeap")||(a.heapAccessShiftForWebGLHeap=()=>k("'heapAccessShiftForWebGLHeap' was not exported. add it to EXPORTED_RUNTIME_METHODS (see the FAQ)"));Object.getOwnPropertyDescriptor(a,"GL")||(a.GL=()=>k("'GL' was not exported. add it to EXPORTED_RUNTIME_METHODS (see the FAQ)"));
Object.getOwnPropertyDescriptor(a,"emscriptenWebGLGet")||(a.emscriptenWebGLGet=()=>k("'emscriptenWebGLGet' was not exported. add it to EXPORTED_RUNTIME_METHODS (see the FAQ)"));Object.getOwnPropertyDescriptor(a,"computeUnpackAlignedImageSize")||(a.computeUnpackAlignedImageSize=()=>k("'computeUnpackAlignedImageSize' was not exported. add it to EXPORTED_RUNTIME_METHODS (see the FAQ)"));Object.getOwnPropertyDescriptor(a,"emscriptenWebGLGetTexPixelData")||(a.emscriptenWebGLGetTexPixelData=()=>k("'emscriptenWebGLGetTexPixelData' was not exported. add it to EXPORTED_RUNTIME_METHODS (see the FAQ)"));
Object.getOwnPropertyDescriptor(a,"emscriptenWebGLGetUniform")||(a.emscriptenWebGLGetUniform=()=>k("'emscriptenWebGLGetUniform' was not exported. add it to EXPORTED_RUNTIME_METHODS (see the FAQ)"));Object.getOwnPropertyDescriptor(a,"webglGetUniformLocation")||(a.webglGetUniformLocation=()=>k("'webglGetUniformLocation' was not exported. add it to EXPORTED_RUNTIME_METHODS (see the FAQ)"));
Object.getOwnPropertyDescriptor(a,"webglPrepareUniformLocationsBeforeFirstUse")||(a.webglPrepareUniformLocationsBeforeFirstUse=()=>k("'webglPrepareUniformLocationsBeforeFirstUse' was not exported. add it to EXPORTED_RUNTIME_METHODS (see the FAQ)"));Object.getOwnPropertyDescriptor(a,"webglGetLeftBracePos")||(a.webglGetLeftBracePos=()=>k("'webglGetLeftBracePos' was not exported. add it to EXPORTED_RUNTIME_METHODS (see the FAQ)"));
Object.getOwnPropertyDescriptor(a,"emscriptenWebGLGetVertexAttrib")||(a.emscriptenWebGLGetVertexAttrib=()=>k("'emscriptenWebGLGetVertexAttrib' was not exported. add it to EXPORTED_RUNTIME_METHODS (see the FAQ)"));Object.getOwnPropertyDescriptor(a,"writeGLArray")||(a.writeGLArray=()=>k("'writeGLArray' was not exported. add it to EXPORTED_RUNTIME_METHODS (see the FAQ)"));Object.getOwnPropertyDescriptor(a,"AL")||(a.AL=()=>k("'AL' was not exported. add it to EXPORTED_RUNTIME_METHODS (see the FAQ)"));
Object.getOwnPropertyDescriptor(a,"SDL_unicode")||(a.SDL_unicode=()=>k("'SDL_unicode' was not exported. add it to EXPORTED_RUNTIME_METHODS (see the FAQ)"));Object.getOwnPropertyDescriptor(a,"SDL_ttfContext")||(a.SDL_ttfContext=()=>k("'SDL_ttfContext' was not exported. add it to EXPORTED_RUNTIME_METHODS (see the FAQ)"));Object.getOwnPropertyDescriptor(a,"SDL_audio")||(a.SDL_audio=()=>k("'SDL_audio' was not exported. add it to EXPORTED_RUNTIME_METHODS (see the FAQ)"));
Object.getOwnPropertyDescriptor(a,"SDL")||(a.SDL=()=>k("'SDL' was not exported. add it to EXPORTED_RUNTIME_METHODS (see the FAQ)"));Object.getOwnPropertyDescriptor(a,"SDL_gfx")||(a.SDL_gfx=()=>k("'SDL_gfx' was not exported. add it to EXPORTED_RUNTIME_METHODS (see the FAQ)"));Object.getOwnPropertyDescriptor(a,"GLUT")||(a.GLUT=()=>k("'GLUT' was not exported. add it to EXPORTED_RUNTIME_METHODS (see the FAQ)"));Object.getOwnPropertyDescriptor(a,"EGL")||(a.EGL=()=>k("'EGL' was not exported. add it to EXPORTED_RUNTIME_METHODS (see the FAQ)"));
Object.getOwnPropertyDescriptor(a,"GLFW_Window")||(a.GLFW_Window=()=>k("'GLFW_Window' was not exported. add it to EXPORTED_RUNTIME_METHODS (see the FAQ)"));Object.getOwnPropertyDescriptor(a,"GLFW")||(a.GLFW=()=>k("'GLFW' was not exported. add it to EXPORTED_RUNTIME_METHODS (see the FAQ)"));Object.getOwnPropertyDescriptor(a,"GLEW")||(a.GLEW=()=>k("'GLEW' was not exported. add it to EXPORTED_RUNTIME_METHODS (see the FAQ)"));Object.getOwnPropertyDescriptor(a,"IDBStore")||(a.IDBStore=()=>k("'IDBStore' was not exported. add it to EXPORTED_RUNTIME_METHODS (see the FAQ)"));
Object.getOwnPropertyDescriptor(a,"runAndAbortIfError")||(a.runAndAbortIfError=()=>k("'runAndAbortIfError' was not exported. add it to EXPORTED_RUNTIME_METHODS (see the FAQ)"));Object.getOwnPropertyDescriptor(a,"warnOnce")||(a.warnOnce=()=>k("'warnOnce' was not exported. add it to EXPORTED_RUNTIME_METHODS (see the FAQ)"));Object.getOwnPropertyDescriptor(a,"stackSave")||(a.stackSave=()=>k("'stackSave' was not exported. add it to EXPORTED_RUNTIME_METHODS (see the FAQ)"));
Object.getOwnPropertyDescriptor(a,"stackRestore")||(a.stackRestore=()=>k("'stackRestore' was not exported. add it to EXPORTED_RUNTIME_METHODS (see the FAQ)"));Object.getOwnPropertyDescriptor(a,"stackAlloc")||(a.stackAlloc=()=>k("'stackAlloc' was not exported. add it to EXPORTED_RUNTIME_METHODS (see the FAQ)"));Object.getOwnPropertyDescriptor(a,"AsciiToString")||(a.AsciiToString=()=>k("'AsciiToString' was not exported. add it to EXPORTED_RUNTIME_METHODS (see the FAQ)"));
Object.getOwnPropertyDescriptor(a,"stringToAscii")||(a.stringToAscii=()=>k("'stringToAscii' was not exported. add it to EXPORTED_RUNTIME_METHODS (see the FAQ)"));Object.getOwnPropertyDescriptor(a,"UTF16ToString")||(a.UTF16ToString=()=>k("'UTF16ToString' was not exported. add it to EXPORTED_RUNTIME_METHODS (see the FAQ)"));Object.getOwnPropertyDescriptor(a,"stringToUTF16")||(a.stringToUTF16=()=>k("'stringToUTF16' was not exported. add it to EXPORTED_RUNTIME_METHODS (see the FAQ)"));
Object.getOwnPropertyDescriptor(a,"lengthBytesUTF16")||(a.lengthBytesUTF16=()=>k("'lengthBytesUTF16' was not exported. add it to EXPORTED_RUNTIME_METHODS (see the FAQ)"));Object.getOwnPropertyDescriptor(a,"UTF32ToString")||(a.UTF32ToString=()=>k("'UTF32ToString' was not exported. add it to EXPORTED_RUNTIME_METHODS (see the FAQ)"));Object.getOwnPropertyDescriptor(a,"stringToUTF32")||(a.stringToUTF32=()=>k("'stringToUTF32' was not exported. add it to EXPORTED_RUNTIME_METHODS (see the FAQ)"));
Object.getOwnPropertyDescriptor(a,"lengthBytesUTF32")||(a.lengthBytesUTF32=()=>k("'lengthBytesUTF32' was not exported. add it to EXPORTED_RUNTIME_METHODS (see the FAQ)"));Object.getOwnPropertyDescriptor(a,"allocateUTF8")||(a.allocateUTF8=()=>k("'allocateUTF8' was not exported. add it to EXPORTED_RUNTIME_METHODS (see the FAQ)"));Object.getOwnPropertyDescriptor(a,"allocateUTF8OnStack")||(a.allocateUTF8OnStack=()=>k("'allocateUTF8OnStack' was not exported. add it to EXPORTED_RUNTIME_METHODS (see the FAQ)"));
a.writeStackCookie=K;a.checkStackCookie=M;Object.getOwnPropertyDescriptor(a,"ALLOC_NORMAL")||Object.defineProperty(a,"ALLOC_NORMAL",{configurable:!0,get:function(){k("'ALLOC_NORMAL' was not exported. add it to EXPORTED_RUNTIME_METHODS (see the FAQ)")}});Object.getOwnPropertyDescriptor(a,"ALLOC_STACK")||Object.defineProperty(a,"ALLOC_STACK",{configurable:!0,get:function(){k("'ALLOC_STACK' was not exported. add it to EXPORTED_RUNTIME_METHODS (see the FAQ)")}});var Y;S=function ra(){Y||Z();Y||(S=ra)};
function Z(){function c(){if(!Y&&(Y=!0,a.calledRun=!0,!D)){M();assert(!P);P=!0;W(ba);b(a);if(a.onRuntimeInitialized)a.onRuntimeInitialized();assert(!a._main,'compiled without a main, but one is present. if you added it from JS, use Module["onRuntimeInitialized"]');M();if(a.postRun)for("function"==typeof a.postRun&&(a.postRun=[a.postRun]);a.postRun.length;){var d=a.postRun.shift();ca.unshift(d)}W(ca)}}if(!(0<Q)){qa();K();if(a.preRun)for("function"==typeof a.preRun&&(a.preRun=[a.preRun]);a.preRun.length;)da();
W(aa);0<Q||(a.setStatus?(a.setStatus("Running..."),setTimeout(function(){setTimeout(function(){a.setStatus("")},1);c()},1)):c(),M())}}a.run=Z;if(a.preInit)for("function"==typeof a.preInit&&(a.preInit=[a.preInit]);0<a.preInit.length;)a.preInit.pop()();Z();


  return WasmPitchModule.ready
}
);
})();
export default WasmPitchModule;