
var Module = (function() {
  var _scriptDir = typeof document !== 'undefined' && document.currentScript ? document.currentScript.src : undefined;
  if (typeof __filename !== 'undefined') _scriptDir = _scriptDir || __filename;
  return (
function(Module) {
  Module = Module || {};


var a;a||(a=typeof Module !== 'undefined' ? Module : {});var b,f;a.ready=new Promise(function(c,d){b=c;f=d});Object.getOwnPropertyDescriptor(a.ready,"_main")||(Object.defineProperty(a.ready,"_main",{configurable:!0,get:function(){g("You are getting _main on the Promise object, instead of the instance. Use .then() to get called back with the instance, see the MODULARIZE docs in src/settings.js")}}),Object.defineProperty(a.ready,"_main",{configurable:!0,set:function(){g("You are setting _main on the Promise object, instead of the instance. Use .then() to get called back with the instance, see the MODULARIZE docs in src/settings.js")}}));
Object.getOwnPropertyDescriptor(a.ready,"_stackSave")||(Object.defineProperty(a.ready,"_stackSave",{configurable:!0,get:function(){g("You are getting _stackSave on the Promise object, instead of the instance. Use .then() to get called back with the instance, see the MODULARIZE docs in src/settings.js")}}),Object.defineProperty(a.ready,"_stackSave",{configurable:!0,set:function(){g("You are setting _stackSave on the Promise object, instead of the instance. Use .then() to get called back with the instance, see the MODULARIZE docs in src/settings.js")}}));
Object.getOwnPropertyDescriptor(a.ready,"_stackRestore")||(Object.defineProperty(a.ready,"_stackRestore",{configurable:!0,get:function(){g("You are getting _stackRestore on the Promise object, instead of the instance. Use .then() to get called back with the instance, see the MODULARIZE docs in src/settings.js")}}),Object.defineProperty(a.ready,"_stackRestore",{configurable:!0,set:function(){g("You are setting _stackRestore on the Promise object, instead of the instance. Use .then() to get called back with the instance, see the MODULARIZE docs in src/settings.js")}}));
Object.getOwnPropertyDescriptor(a.ready,"_stackAlloc")||(Object.defineProperty(a.ready,"_stackAlloc",{configurable:!0,get:function(){g("You are getting _stackAlloc on the Promise object, instead of the instance. Use .then() to get called back with the instance, see the MODULARIZE docs in src/settings.js")}}),Object.defineProperty(a.ready,"_stackAlloc",{configurable:!0,set:function(){g("You are setting _stackAlloc on the Promise object, instead of the instance. Use .then() to get called back with the instance, see the MODULARIZE docs in src/settings.js")}}));
Object.getOwnPropertyDescriptor(a.ready,"___data_end")||(Object.defineProperty(a.ready,"___data_end",{configurable:!0,get:function(){g("You are getting ___data_end on the Promise object, instead of the instance. Use .then() to get called back with the instance, see the MODULARIZE docs in src/settings.js")}}),Object.defineProperty(a.ready,"___data_end",{configurable:!0,set:function(){g("You are setting ___data_end on the Promise object, instead of the instance. Use .then() to get called back with the instance, see the MODULARIZE docs in src/settings.js")}}));
Object.getOwnPropertyDescriptor(a.ready,"___wasm_call_ctors")||(Object.defineProperty(a.ready,"___wasm_call_ctors",{configurable:!0,get:function(){g("You are getting ___wasm_call_ctors on the Promise object, instead of the instance. Use .then() to get called back with the instance, see the MODULARIZE docs in src/settings.js")}}),Object.defineProperty(a.ready,"___wasm_call_ctors",{configurable:!0,set:function(){g("You are setting ___wasm_call_ctors on the Promise object, instead of the instance. Use .then() to get called back with the instance, see the MODULARIZE docs in src/settings.js")}}));
Object.getOwnPropertyDescriptor(a.ready,"_fflush")||(Object.defineProperty(a.ready,"_fflush",{configurable:!0,get:function(){g("You are getting _fflush on the Promise object, instead of the instance. Use .then() to get called back with the instance, see the MODULARIZE docs in src/settings.js")}}),Object.defineProperty(a.ready,"_fflush",{configurable:!0,set:function(){g("You are setting _fflush on the Promise object, instead of the instance. Use .then() to get called back with the instance, see the MODULARIZE docs in src/settings.js")}}));
Object.getOwnPropertyDescriptor(a.ready,"___errno_location")||(Object.defineProperty(a.ready,"___errno_location",{configurable:!0,get:function(){g("You are getting ___errno_location on the Promise object, instead of the instance. Use .then() to get called back with the instance, see the MODULARIZE docs in src/settings.js")}}),Object.defineProperty(a.ready,"___errno_location",{configurable:!0,set:function(){g("You are setting ___errno_location on the Promise object, instead of the instance. Use .then() to get called back with the instance, see the MODULARIZE docs in src/settings.js")}}));
Object.getOwnPropertyDescriptor(a.ready,"_malloc")||(Object.defineProperty(a.ready,"_malloc",{configurable:!0,get:function(){g("You are getting _malloc on the Promise object, instead of the instance. Use .then() to get called back with the instance, see the MODULARIZE docs in src/settings.js")}}),Object.defineProperty(a.ready,"_malloc",{configurable:!0,set:function(){g("You are setting _malloc on the Promise object, instead of the instance. Use .then() to get called back with the instance, see the MODULARIZE docs in src/settings.js")}}));
Object.getOwnPropertyDescriptor(a.ready,"_free")||(Object.defineProperty(a.ready,"_free",{configurable:!0,get:function(){g("You are getting _free on the Promise object, instead of the instance. Use .then() to get called back with the instance, see the MODULARIZE docs in src/settings.js")}}),Object.defineProperty(a.ready,"_free",{configurable:!0,set:function(){g("You are setting _free on the Promise object, instead of the instance. Use .then() to get called back with the instance, see the MODULARIZE docs in src/settings.js")}}));
Object.getOwnPropertyDescriptor(a.ready,"_setThrew")||(Object.defineProperty(a.ready,"_setThrew",{configurable:!0,get:function(){g("You are getting _setThrew on the Promise object, instead of the instance. Use .then() to get called back with the instance, see the MODULARIZE docs in src/settings.js")}}),Object.defineProperty(a.ready,"_setThrew",{configurable:!0,set:function(){g("You are setting _setThrew on the Promise object, instead of the instance. Use .then() to get called back with the instance, see the MODULARIZE docs in src/settings.js")}}));
Object.getOwnPropertyDescriptor(a.ready,"onRuntimeInitialized")||(Object.defineProperty(a.ready,"onRuntimeInitialized",{configurable:!0,get:function(){g("You are getting onRuntimeInitialized on the Promise object, instead of the instance. Use .then() to get called back with the instance, see the MODULARIZE docs in src/settings.js")}}),Object.defineProperty(a.ready,"onRuntimeInitialized",{configurable:!0,set:function(){g("You are setting onRuntimeInitialized on the Promise object, instead of the instance. Use .then() to get called back with the instance, see the MODULARIZE docs in src/settings.js")}}));
var k={},l;for(l in a)a.hasOwnProperty(l)&&(k[l]=a[l]);var m=!1,n=!1,p=!1,q=!1;m="object"===typeof window;n="function"===typeof importScripts;p="object"===typeof process&&"object"===typeof process.versions&&"string"===typeof process.versions.node;q=!m&&!p&&!n;if(a.ENVIRONMENT)throw Error("Module.ENVIRONMENT has been deprecated. To force the environment, use the ENVIRONMENT compile-time option (for example, -s ENVIRONMENT=web or -s ENVIRONMENT=node)");var r="",t,u,w,x;
if(p)r=n?require("path").dirname(r)+"/":__dirname+"/",t=function(c,d){w||(w=require("fs"));x||(x=require("path"));c=x.normalize(c);return w.readFileSync(c,d?null:"utf8")},u=function(c){c=t(c,!0);c.buffer||(c=new Uint8Array(c));assert(c.buffer);return c},1<process.argv.length&&process.argv[1].replace(/\\/g,"/"),process.argv.slice(2),process.on("uncaughtException",function(c){throw c;}),process.on("unhandledRejection",g),a.inspect=function(){return"[Emscripten Module object]"};else if(q)"undefined"!=
typeof read&&(t=function(c){return read(c)}),u=function(c){if("function"===typeof readbuffer)return new Uint8Array(readbuffer(c));c=read(c,"binary");assert("object"===typeof c);return c},"undefined"!==typeof print&&("undefined"===typeof console&&(console={}),console.log=print,console.warn=console.error="undefined"!==typeof printErr?printErr:print);else if(m||n)n?r=self.location.href:document.currentScript&&(r=document.currentScript.src),_scriptDir&&(r=_scriptDir),0!==r.indexOf("blob:")?r=r.substr(0,
r.lastIndexOf("/")+1):r="",t=function(c){var d=new XMLHttpRequest;d.open("GET",c,!1);d.send(null);return d.responseText},n&&(u=function(c){var d=new XMLHttpRequest;d.open("GET",c,!1);d.responseType="arraybuffer";d.send(null);return new Uint8Array(d.response)});else throw Error("environment detection error");a.print||console.log.bind(console);var y=a.printErr||console.warn.bind(console);for(l in k)k.hasOwnProperty(l)&&(a[l]=k[l]);k=null;
Object.getOwnPropertyDescriptor(a,"arguments")||Object.defineProperty(a,"arguments",{configurable:!0,get:function(){g("Module.arguments has been replaced with plain arguments_ (the initial value can be provided on Module, but after startup the value is only looked for on a local variable of that name)")}});Object.getOwnPropertyDescriptor(a,"thisProgram")||Object.defineProperty(a,"thisProgram",{configurable:!0,get:function(){g("Module.thisProgram has been replaced with plain thisProgram (the initial value can be provided on Module, but after startup the value is only looked for on a local variable of that name)")}});
Object.getOwnPropertyDescriptor(a,"quit")||Object.defineProperty(a,"quit",{configurable:!0,get:function(){g("Module.quit has been replaced with plain quit_ (the initial value can be provided on Module, but after startup the value is only looked for on a local variable of that name)")}});assert("undefined"===typeof a.memoryInitializerPrefixURL,"Module.memoryInitializerPrefixURL option was removed, use Module.locateFile instead");assert("undefined"===typeof a.pthreadMainPrefixURL,"Module.pthreadMainPrefixURL option was removed, use Module.locateFile instead");
assert("undefined"===typeof a.cdInitializerPrefixURL,"Module.cdInitializerPrefixURL option was removed, use Module.locateFile instead");assert("undefined"===typeof a.filePackagePrefixURL,"Module.filePackagePrefixURL option was removed, use Module.locateFile instead");assert("undefined"===typeof a.read,"Module.read option was removed (modify read_ in JS)");assert("undefined"===typeof a.readAsync,"Module.readAsync option was removed (modify readAsync in JS)");
assert("undefined"===typeof a.readBinary,"Module.readBinary option was removed (modify readBinary in JS)");assert("undefined"===typeof a.setWindowTitle,"Module.setWindowTitle option was removed (modify setWindowTitle in JS)");assert("undefined"===typeof a.TOTAL_MEMORY,"Module.TOTAL_MEMORY has been renamed Module.INITIAL_MEMORY");Object.getOwnPropertyDescriptor(a,"read")||Object.defineProperty(a,"read",{configurable:!0,get:function(){g("Module.read has been replaced with plain read_ (the initial value can be provided on Module, but after startup the value is only looked for on a local variable of that name)")}});
Object.getOwnPropertyDescriptor(a,"readAsync")||Object.defineProperty(a,"readAsync",{configurable:!0,get:function(){g("Module.readAsync has been replaced with plain readAsync (the initial value can be provided on Module, but after startup the value is only looked for on a local variable of that name)")}});Object.getOwnPropertyDescriptor(a,"readBinary")||Object.defineProperty(a,"readBinary",{configurable:!0,get:function(){g("Module.readBinary has been replaced with plain readBinary (the initial value can be provided on Module, but after startup the value is only looked for on a local variable of that name)")}});
Object.getOwnPropertyDescriptor(a,"setWindowTitle")||Object.defineProperty(a,"setWindowTitle",{configurable:!0,get:function(){g("Module.setWindowTitle has been replaced with plain setWindowTitle (the initial value can be provided on Module, but after startup the value is only looked for on a local variable of that name)")}});var z,A;a.wasmBinary&&(A=a.wasmBinary);Object.getOwnPropertyDescriptor(a,"wasmBinary")||Object.defineProperty(a,"wasmBinary",{configurable:!0,get:function(){g("Module.wasmBinary has been replaced with plain wasmBinary (the initial value can be provided on Module, but after startup the value is only looked for on a local variable of that name)")}});
var noExitRuntime;a.noExitRuntime&&(noExitRuntime=a.noExitRuntime);Object.getOwnPropertyDescriptor(a,"noExitRuntime")||Object.defineProperty(a,"noExitRuntime",{configurable:!0,get:function(){g("Module.noExitRuntime has been replaced with plain noExitRuntime (the initial value can be provided on Module, but after startup the value is only looked for on a local variable of that name)")}});"object"!==typeof WebAssembly&&g("no native wasm support detected");var B,C,D=!1;
function assert(c,d){c||g("Assertion failed: "+d)}"undefined"!==typeof TextDecoder&&new TextDecoder("utf8");"undefined"!==typeof TextDecoder&&new TextDecoder("utf-16le");var E,F,G,H,I;assert(!0,"stack must start aligned");a.TOTAL_STACK&&assert(5242880===a.TOTAL_STACK,"the stack size can no longer be determined at runtime");var J=a.INITIAL_MEMORY||16777216;Object.getOwnPropertyDescriptor(a,"INITIAL_MEMORY")||Object.defineProperty(a,"INITIAL_MEMORY",{configurable:!0,get:function(){g("Module.INITIAL_MEMORY has been replaced with plain INITIAL_INITIAL_MEMORY (the initial value can be provided on Module, but after startup the value is only looked for on a local variable of that name)")}});
assert(5242880<=J,"INITIAL_MEMORY should be larger than TOTAL_STACK, was "+J+"! (TOTAL_STACK=5242880)");assert("undefined"!==typeof Int32Array&&"undefined"!==typeof Float64Array&&void 0!==Int32Array.prototype.subarray&&void 0!==Int32Array.prototype.set,"JS engine does not provide full typed array support");a.wasmMemory?B=a.wasmMemory:B=new WebAssembly.Memory({initial:J/65536,maximum:J/65536});B&&(E=B.buffer);J=E.byteLength;assert(0===J%65536);var K=E;E=K;a.HEAP8=F=new Int8Array(K);a.HEAP16=new Int16Array(K);
a.HEAP32=H=new Int32Array(K);a.HEAPU8=G=new Uint8Array(K);a.HEAPU16=new Uint16Array(K);a.HEAPU32=I=new Uint32Array(K);a.HEAPF32=new Float32Array(K);a.HEAPF64=new Float64Array(K);function L(){assert(!0);I[529]=34821223;I[530]=2310721022;H[0]=1668509029}
function M(){var c=I[529],d=I[530];34821223==c&&2310721022==d||g("Stack overflow! Stack cookie has been overwritten, expected hex dwords 0x89BACDFE and 0x2135467, but received 0x"+d.toString(16)+" "+c.toString(16));1668509029!==H[0]&&g("Runtime error: The application has corrupted its heap memory area (address zero)!")}var aa=new Int16Array(1),ba=new Int8Array(aa.buffer);aa[0]=25459;if(115!==ba[0]||99!==ba[1])throw"Runtime error: expected the system to be little-endian!";
var ca=[],da=[],ea=[],fa=[],N=!1;function ha(){var c=a.preRun.shift();ca.unshift(c)}assert(Math.imul,"This browser does not support Math.imul(), build with LEGACY_VM_SUPPORT or POLYFILL_OLD_MATH_FUNCTIONS to add in a polyfill");assert(Math.fround,"This browser does not support Math.fround(), build with LEGACY_VM_SUPPORT or POLYFILL_OLD_MATH_FUNCTIONS to add in a polyfill");assert(Math.clz32,"This browser does not support Math.clz32(), build with LEGACY_VM_SUPPORT or POLYFILL_OLD_MATH_FUNCTIONS to add in a polyfill");
assert(Math.trunc,"This browser does not support Math.trunc(), build with LEGACY_VM_SUPPORT or POLYFILL_OLD_MATH_FUNCTIONS to add in a polyfill");var O=0,P=null,Q=null,R={};
function ia(){O++;a.monitorRunDependencies&&a.monitorRunDependencies(O);assert(!R["wasm-instantiate"]);R["wasm-instantiate"]=1;null===P&&"undefined"!==typeof setInterval&&(P=setInterval(function(){if(D)clearInterval(P),P=null;else{var c=!1,d;for(d in R)c||(c=!0,y("still waiting on run dependencies:")),y("dependency: "+d);c&&y("(end of list)")}},1E4))}a.preloadedImages={};a.preloadedAudios={};
function g(c){if(a.onAbort)a.onAbort(c);y(c);D=!0;c="abort("+c+") at ";a:{var d=Error();if(!d.stack){try{throw Error();}catch(e){d=e}if(!d.stack){d="(no stack trace available)";break a}}d=d.stack.toString()}a.extraStackTrace&&(d+="\n"+a.extraStackTrace());d=ja(d);c=new WebAssembly.RuntimeError(c+d);f(c);throw c;}
function ka(){g("Filesystem support (FS) was not included. The problem is that you are using files from JS, but files were not used from C/C++, so filesystem support was not auto-included. You can force-include filesystem support with  -s FORCE_FILESYSTEM=1")}a.FS_createDataFile=function(){ka()};a.FS_createPreloadedFile=function(){ka()};function S(c){var d=U;return String.prototype.startsWith?d.startsWith(c):0===d.indexOf(c)}function ma(){return S("data:application/octet-stream;base64,")}
function V(c){return function(){var d=a.asm;assert(N,"native function `"+c+"` called before runtime initialization");assert(!0,"native function `"+c+"` called after runtime exit (use NO_EXIT_RUNTIME to keep it alive after main() exits)");d[c]||assert(d[c],"exported native function `"+c+"` not found");return d[c].apply(null,arguments)}}var U="wasm_interface.wasm";if(!ma()){var na=U;U=a.locateFile?a.locateFile(na,r):r+na}
function oa(){try{if(A)return new Uint8Array(A);if(u)return u(U);throw"both async and sync fetching of the wasm failed";}catch(c){g(c)}}function pa(){return A||!m&&!n||"function"!==typeof fetch||S("file://")?Promise.resolve().then(oa):fetch(U,{credentials:"same-origin"}).then(function(c){if(!c.ok)throw"failed to load wasm binary file at '"+U+"'";return c.arrayBuffer()}).catch(function(){return oa()})}
function W(c){for(;0<c.length;){var d=c.shift();if("function"==typeof d)d(a);else{var e=d.f;"number"===typeof e?void 0===d.b?C.get(e)():C.get(e)(d.b):e(void 0===d.b?null:d.b)}}}
function ja(c){return c.replace(/\b_Z[\w\d_]+/g,function(d){z||(z={});z["warning: build with  -s DEMANGLE_SUPPORT=1  to link in libcxxabi demangling"]||(z["warning: build with  -s DEMANGLE_SUPPORT=1  to link in libcxxabi demangling"]=1,y("warning: build with  -s DEMANGLE_SUPPORT=1  to link in libcxxabi demangling"));return d===d?d:d+" ["+d+"]"})}
function qa(c){this.a=c-16;this.m=function(d){H[this.a+8>>2]=d};this.i=function(d){H[this.a+0>>2]=d};this.j=function(){H[this.a+4>>2]=0};this.h=function(){F[this.a+12>>0]=0};this.l=function(){F[this.a+13>>0]=0};this.g=function(d,e){this.m(d);this.i(e);this.j();this.h();this.l()}}function X(){return 0<X.c}da.push({f:function(){ra()}});
var ta={__cxa_allocate_exception:function(c){return sa(c+16)+16},__cxa_throw:function(c,d,e){(new qa(c)).g(d,e);"uncaught_exception"in X?X.c++:X.c=1;throw c+" - Exception catching is disabled, this exception cannot be caught. Compile with -s DISABLE_EXCEPTION_CATCHING=0 or DISABLE_EXCEPTION_CATCHING=2 to catch.";},abort:function(){g()},emscripten_memcpy_big:function(c,d,e){G.copyWithin(c,d,d+e)},emscripten_resize_heap:function(c){g("Cannot enlarge memory arrays to size "+(c>>>0)+" bytes (OOM). Either (1) compile with  -s INITIAL_MEMORY=X  with X higher than the current value "+
F.length+", (2) compile with  -s ALLOW_MEMORY_GROWTH=1  which allows increasing the size at runtime, or (3) if you want malloc to return NULL (0) instead of this abort, compile with  -s ABORTING_MALLOC=0 ")},memory:B};
(function(){function c(h){a.asm=h.exports;C=a.asm.__indirect_function_table;assert(C,"table not found in wasm exports");O--;a.monitorRunDependencies&&a.monitorRunDependencies(O);assert(R["wasm-instantiate"]);delete R["wasm-instantiate"];0==O&&(null!==P&&(clearInterval(P),P=null),Q&&(h=Q,Q=null,h()))}function d(h){assert(a===la,"the Module object should not be replaced during async compilation - perhaps the order of HTML elements is wrong?");la=null;c(h.instance)}function e(h){return pa().then(function(v){return WebAssembly.instantiate(v,
T)}).then(h,function(v){y("failed to asynchronously prepare wasm: "+v);g(v)})}var T={env:ta,wasi_snapshot_preview1:ta};ia();var la=a;if(a.instantiateWasm)try{return a.instantiateWasm(T,c)}catch(h){return y("Module.instantiateWasm callback failed with error: "+h),!1}(function(){if(A||"function"!==typeof WebAssembly.instantiateStreaming||ma()||S("file://")||"function"!==typeof fetch)return e(d);fetch(U,{credentials:"same-origin"}).then(function(h){return WebAssembly.instantiateStreaming(h,T).then(d,
function(v){y("wasm streaming compile failed: "+v);y("falling back to ArrayBuffer instantiation");return e(d)})})})();return{}})();var ra=a.___wasm_call_ctors=V("__wasm_call_ctors");a._get_pitch_mpm_c=V("get_pitch_mpm_c");a.___errno_location=V("__errno_location");a._fflush=V("fflush");a.stackSave=V("stackSave");a.stackRestore=V("stackRestore");a.stackAlloc=V("stackAlloc");a._setThrew=V("setThrew");var sa=a._malloc=V("malloc");a._free=V("free");a.__growWasmMemory=V("__growWasmMemory");
Object.getOwnPropertyDescriptor(a,"intArrayFromString")||(a.intArrayFromString=function(){g("'intArrayFromString' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"intArrayToString")||(a.intArrayToString=function(){g("'intArrayToString' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"ccall")||(a.ccall=function(){g("'ccall' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"cwrap")||(a.cwrap=function(){g("'cwrap' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"setValue")||(a.setValue=function(){g("'setValue' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"getValue")||(a.getValue=function(){g("'getValue' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"allocate")||(a.allocate=function(){g("'allocate' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"UTF8ArrayToString")||(a.UTF8ArrayToString=function(){g("'UTF8ArrayToString' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"UTF8ToString")||(a.UTF8ToString=function(){g("'UTF8ToString' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"stringToUTF8Array")||(a.stringToUTF8Array=function(){g("'stringToUTF8Array' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"stringToUTF8")||(a.stringToUTF8=function(){g("'stringToUTF8' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"lengthBytesUTF8")||(a.lengthBytesUTF8=function(){g("'lengthBytesUTF8' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"stackTrace")||(a.stackTrace=function(){g("'stackTrace' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"addOnPreRun")||(a.addOnPreRun=function(){g("'addOnPreRun' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"addOnInit")||(a.addOnInit=function(){g("'addOnInit' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"addOnPreMain")||(a.addOnPreMain=function(){g("'addOnPreMain' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"addOnExit")||(a.addOnExit=function(){g("'addOnExit' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"addOnPostRun")||(a.addOnPostRun=function(){g("'addOnPostRun' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"writeStringToMemory")||(a.writeStringToMemory=function(){g("'writeStringToMemory' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"writeArrayToMemory")||(a.writeArrayToMemory=function(){g("'writeArrayToMemory' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"writeAsciiToMemory")||(a.writeAsciiToMemory=function(){g("'writeAsciiToMemory' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"addRunDependency")||(a.addRunDependency=function(){g("'addRunDependency' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ). Alternatively, forcing filesystem support (-s FORCE_FILESYSTEM=1) can export this for you")});Object.getOwnPropertyDescriptor(a,"removeRunDependency")||(a.removeRunDependency=function(){g("'removeRunDependency' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ). Alternatively, forcing filesystem support (-s FORCE_FILESYSTEM=1) can export this for you")});
Object.getOwnPropertyDescriptor(a,"FS_createFolder")||(a.FS_createFolder=function(){g("'FS_createFolder' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"FS_createPath")||(a.FS_createPath=function(){g("'FS_createPath' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ). Alternatively, forcing filesystem support (-s FORCE_FILESYSTEM=1) can export this for you")});
Object.getOwnPropertyDescriptor(a,"FS_createDataFile")||(a.FS_createDataFile=function(){g("'FS_createDataFile' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ). Alternatively, forcing filesystem support (-s FORCE_FILESYSTEM=1) can export this for you")});Object.getOwnPropertyDescriptor(a,"FS_createPreloadedFile")||(a.FS_createPreloadedFile=function(){g("'FS_createPreloadedFile' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ). Alternatively, forcing filesystem support (-s FORCE_FILESYSTEM=1) can export this for you")});
Object.getOwnPropertyDescriptor(a,"FS_createLazyFile")||(a.FS_createLazyFile=function(){g("'FS_createLazyFile' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ). Alternatively, forcing filesystem support (-s FORCE_FILESYSTEM=1) can export this for you")});Object.getOwnPropertyDescriptor(a,"FS_createLink")||(a.FS_createLink=function(){g("'FS_createLink' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"FS_createDevice")||(a.FS_createDevice=function(){g("'FS_createDevice' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ). Alternatively, forcing filesystem support (-s FORCE_FILESYSTEM=1) can export this for you")});Object.getOwnPropertyDescriptor(a,"FS_unlink")||(a.FS_unlink=function(){g("'FS_unlink' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ). Alternatively, forcing filesystem support (-s FORCE_FILESYSTEM=1) can export this for you")});
Object.getOwnPropertyDescriptor(a,"getLEB")||(a.getLEB=function(){g("'getLEB' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"getFunctionTables")||(a.getFunctionTables=function(){g("'getFunctionTables' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"alignFunctionTables")||(a.alignFunctionTables=function(){g("'alignFunctionTables' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"registerFunctions")||(a.registerFunctions=function(){g("'registerFunctions' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"addFunction")||(a.addFunction=function(){g("'addFunction' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"removeFunction")||(a.removeFunction=function(){g("'removeFunction' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"getFuncWrapper")||(a.getFuncWrapper=function(){g("'getFuncWrapper' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"prettyPrint")||(a.prettyPrint=function(){g("'prettyPrint' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"makeBigInt")||(a.makeBigInt=function(){g("'makeBigInt' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"dynCall")||(a.dynCall=function(){g("'dynCall' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"getCompilerSetting")||(a.getCompilerSetting=function(){g("'getCompilerSetting' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"print")||(a.print=function(){g("'print' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"printErr")||(a.printErr=function(){g("'printErr' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"getTempRet0")||(a.getTempRet0=function(){g("'getTempRet0' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"setTempRet0")||(a.setTempRet0=function(){g("'setTempRet0' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"callMain")||(a.callMain=function(){g("'callMain' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"abort")||(a.abort=function(){g("'abort' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"stringToNewUTF8")||(a.stringToNewUTF8=function(){g("'stringToNewUTF8' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"abortOnCannotGrowMemory")||(a.abortOnCannotGrowMemory=function(){g("'abortOnCannotGrowMemory' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"emscripten_realloc_buffer")||(a.emscripten_realloc_buffer=function(){g("'emscripten_realloc_buffer' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"ENV")||(a.ENV=function(){g("'ENV' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"ERRNO_CODES")||(a.ERRNO_CODES=function(){g("'ERRNO_CODES' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"ERRNO_MESSAGES")||(a.ERRNO_MESSAGES=function(){g("'ERRNO_MESSAGES' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"setErrNo")||(a.setErrNo=function(){g("'setErrNo' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"DNS")||(a.DNS=function(){g("'DNS' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"getHostByName")||(a.getHostByName=function(){g("'getHostByName' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"GAI_ERRNO_MESSAGES")||(a.GAI_ERRNO_MESSAGES=function(){g("'GAI_ERRNO_MESSAGES' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"Protocols")||(a.Protocols=function(){g("'Protocols' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"Sockets")||(a.Sockets=function(){g("'Sockets' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"getRandomDevice")||(a.getRandomDevice=function(){g("'getRandomDevice' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"traverseStack")||(a.traverseStack=function(){g("'traverseStack' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"UNWIND_CACHE")||(a.UNWIND_CACHE=function(){g("'UNWIND_CACHE' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"withBuiltinMalloc")||(a.withBuiltinMalloc=function(){g("'withBuiltinMalloc' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"readAsmConstArgsArray")||(a.readAsmConstArgsArray=function(){g("'readAsmConstArgsArray' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"readAsmConstArgs")||(a.readAsmConstArgs=function(){g("'readAsmConstArgs' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"mainThreadEM_ASM")||(a.mainThreadEM_ASM=function(){g("'mainThreadEM_ASM' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"jstoi_q")||(a.jstoi_q=function(){g("'jstoi_q' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"jstoi_s")||(a.jstoi_s=function(){g("'jstoi_s' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"getExecutableName")||(a.getExecutableName=function(){g("'getExecutableName' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"listenOnce")||(a.listenOnce=function(){g("'listenOnce' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"autoResumeAudioContext")||(a.autoResumeAudioContext=function(){g("'autoResumeAudioContext' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"dynCallLegacy")||(a.dynCallLegacy=function(){g("'dynCallLegacy' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"getDynCaller")||(a.getDynCaller=function(){g("'getDynCaller' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"dynCall")||(a.dynCall=function(){g("'dynCall' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"callRuntimeCallbacks")||(a.callRuntimeCallbacks=function(){g("'callRuntimeCallbacks' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"abortStackOverflow")||(a.abortStackOverflow=function(){g("'abortStackOverflow' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"reallyNegative")||(a.reallyNegative=function(){g("'reallyNegative' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"unSign")||(a.unSign=function(){g("'unSign' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"reSign")||(a.reSign=function(){g("'reSign' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"formatString")||(a.formatString=function(){g("'formatString' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"PATH")||(a.PATH=function(){g("'PATH' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"PATH_FS")||(a.PATH_FS=function(){g("'PATH_FS' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"SYSCALLS")||(a.SYSCALLS=function(){g("'SYSCALLS' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"syscallMmap2")||(a.syscallMmap2=function(){g("'syscallMmap2' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"syscallMunmap")||(a.syscallMunmap=function(){g("'syscallMunmap' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"flush_NO_FILESYSTEM")||(a.flush_NO_FILESYSTEM=function(){g("'flush_NO_FILESYSTEM' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"JSEvents")||(a.JSEvents=function(){g("'JSEvents' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"specialHTMLTargets")||(a.specialHTMLTargets=function(){g("'specialHTMLTargets' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"maybeCStringToJsString")||(a.maybeCStringToJsString=function(){g("'maybeCStringToJsString' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"findEventTarget")||(a.findEventTarget=function(){g("'findEventTarget' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"findCanvasEventTarget")||(a.findCanvasEventTarget=function(){g("'findCanvasEventTarget' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"polyfillSetImmediate")||(a.polyfillSetImmediate=function(){g("'polyfillSetImmediate' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"demangle")||(a.demangle=function(){g("'demangle' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"demangleAll")||(a.demangleAll=function(){g("'demangleAll' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"jsStackTrace")||(a.jsStackTrace=function(){g("'jsStackTrace' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"stackTrace")||(a.stackTrace=function(){g("'stackTrace' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"getEnvStrings")||(a.getEnvStrings=function(){g("'getEnvStrings' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"checkWasiClock")||(a.checkWasiClock=function(){g("'checkWasiClock' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"writeI53ToI64")||(a.writeI53ToI64=function(){g("'writeI53ToI64' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"writeI53ToI64Clamped")||(a.writeI53ToI64Clamped=function(){g("'writeI53ToI64Clamped' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"writeI53ToI64Signaling")||(a.writeI53ToI64Signaling=function(){g("'writeI53ToI64Signaling' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"writeI53ToU64Clamped")||(a.writeI53ToU64Clamped=function(){g("'writeI53ToU64Clamped' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"writeI53ToU64Signaling")||(a.writeI53ToU64Signaling=function(){g("'writeI53ToU64Signaling' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"readI53FromI64")||(a.readI53FromI64=function(){g("'readI53FromI64' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"readI53FromU64")||(a.readI53FromU64=function(){g("'readI53FromU64' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"convertI32PairToI53")||(a.convertI32PairToI53=function(){g("'convertI32PairToI53' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"convertU32PairToI53")||(a.convertU32PairToI53=function(){g("'convertU32PairToI53' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"exceptionLast")||(a.exceptionLast=function(){g("'exceptionLast' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"exceptionCaught")||(a.exceptionCaught=function(){g("'exceptionCaught' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"ExceptionInfoAttrs")||(a.ExceptionInfoAttrs=function(){g("'ExceptionInfoAttrs' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"ExceptionInfo")||(a.ExceptionInfo=function(){g("'ExceptionInfo' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"CatchInfo")||(a.CatchInfo=function(){g("'CatchInfo' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"exception_addRef")||(a.exception_addRef=function(){g("'exception_addRef' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"exception_decRef")||(a.exception_decRef=function(){g("'exception_decRef' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"Browser")||(a.Browser=function(){g("'Browser' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"funcWrappers")||(a.funcWrappers=function(){g("'funcWrappers' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"getFuncWrapper")||(a.getFuncWrapper=function(){g("'getFuncWrapper' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"setMainLoop")||(a.setMainLoop=function(){g("'setMainLoop' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"FS")||(a.FS=function(){g("'FS' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"mmapAlloc")||(a.mmapAlloc=function(){g("'mmapAlloc' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"MEMFS")||(a.MEMFS=function(){g("'MEMFS' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"TTY")||(a.TTY=function(){g("'TTY' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"PIPEFS")||(a.PIPEFS=function(){g("'PIPEFS' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"SOCKFS")||(a.SOCKFS=function(){g("'SOCKFS' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"tempFixedLengthArray")||(a.tempFixedLengthArray=function(){g("'tempFixedLengthArray' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"miniTempWebGLFloatBuffers")||(a.miniTempWebGLFloatBuffers=function(){g("'miniTempWebGLFloatBuffers' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"heapObjectForWebGLType")||(a.heapObjectForWebGLType=function(){g("'heapObjectForWebGLType' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"heapAccessShiftForWebGLHeap")||(a.heapAccessShiftForWebGLHeap=function(){g("'heapAccessShiftForWebGLHeap' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"GL")||(a.GL=function(){g("'GL' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"emscriptenWebGLGet")||(a.emscriptenWebGLGet=function(){g("'emscriptenWebGLGet' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"computeUnpackAlignedImageSize")||(a.computeUnpackAlignedImageSize=function(){g("'computeUnpackAlignedImageSize' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"emscriptenWebGLGetTexPixelData")||(a.emscriptenWebGLGetTexPixelData=function(){g("'emscriptenWebGLGetTexPixelData' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"emscriptenWebGLGetUniform")||(a.emscriptenWebGLGetUniform=function(){g("'emscriptenWebGLGetUniform' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"emscriptenWebGLGetVertexAttrib")||(a.emscriptenWebGLGetVertexAttrib=function(){g("'emscriptenWebGLGetVertexAttrib' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"writeGLArray")||(a.writeGLArray=function(){g("'writeGLArray' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"AL")||(a.AL=function(){g("'AL' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"SDL_unicode")||(a.SDL_unicode=function(){g("'SDL_unicode' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"SDL_ttfContext")||(a.SDL_ttfContext=function(){g("'SDL_ttfContext' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"SDL_audio")||(a.SDL_audio=function(){g("'SDL_audio' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"SDL")||(a.SDL=function(){g("'SDL' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"SDL_gfx")||(a.SDL_gfx=function(){g("'SDL_gfx' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"GLUT")||(a.GLUT=function(){g("'GLUT' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"EGL")||(a.EGL=function(){g("'EGL' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"GLFW_Window")||(a.GLFW_Window=function(){g("'GLFW_Window' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"GLFW")||(a.GLFW=function(){g("'GLFW' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"GLEW")||(a.GLEW=function(){g("'GLEW' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"IDBStore")||(a.IDBStore=function(){g("'IDBStore' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"runAndAbortIfError")||(a.runAndAbortIfError=function(){g("'runAndAbortIfError' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"warnOnce")||(a.warnOnce=function(){g("'warnOnce' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"stackSave")||(a.stackSave=function(){g("'stackSave' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"stackRestore")||(a.stackRestore=function(){g("'stackRestore' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"stackAlloc")||(a.stackAlloc=function(){g("'stackAlloc' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"AsciiToString")||(a.AsciiToString=function(){g("'AsciiToString' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"stringToAscii")||(a.stringToAscii=function(){g("'stringToAscii' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"UTF16ToString")||(a.UTF16ToString=function(){g("'UTF16ToString' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"stringToUTF16")||(a.stringToUTF16=function(){g("'stringToUTF16' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"lengthBytesUTF16")||(a.lengthBytesUTF16=function(){g("'lengthBytesUTF16' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"UTF32ToString")||(a.UTF32ToString=function(){g("'UTF32ToString' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"stringToUTF32")||(a.stringToUTF32=function(){g("'stringToUTF32' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"lengthBytesUTF32")||(a.lengthBytesUTF32=function(){g("'lengthBytesUTF32' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"allocateUTF8")||(a.allocateUTF8=function(){g("'allocateUTF8' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"allocateUTF8OnStack")||(a.allocateUTF8OnStack=function(){g("'allocateUTF8OnStack' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});a.writeStackCookie=L;a.checkStackCookie=M;
Object.getOwnPropertyDescriptor(a,"ALLOC_NORMAL")||Object.defineProperty(a,"ALLOC_NORMAL",{configurable:!0,get:function(){g("'ALLOC_NORMAL' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")}});Object.getOwnPropertyDescriptor(a,"ALLOC_STACK")||Object.defineProperty(a,"ALLOC_STACK",{configurable:!0,get:function(){g("'ALLOC_STACK' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")}});var Y;Q=function ua(){Y||Z();Y||(Q=ua)};
function Z(){function c(){if(!Y&&(Y=!0,a.calledRun=!0,!D)){M();assert(!N);N=!0;W(da);M();W(ea);b(a);if(a.onRuntimeInitialized)a.onRuntimeInitialized();assert(!a._main,'compiled without a main, but one is present. if you added it from JS, use Module["onRuntimeInitialized"]');M();if(a.postRun)for("function"==typeof a.postRun&&(a.postRun=[a.postRun]);a.postRun.length;){var d=a.postRun.shift();fa.unshift(d)}W(fa)}}if(!(0<O)){L();if(a.preRun)for("function"==typeof a.preRun&&(a.preRun=[a.preRun]);a.preRun.length;)ha();
W(ca);0<O||(a.setStatus?(a.setStatus("Running..."),setTimeout(function(){setTimeout(function(){a.setStatus("")},1);c()},1)):c(),D||M())}}a.run=Z;if(a.preInit)for("function"==typeof a.preInit&&(a.preInit=[a.preInit]);0<a.preInit.length;)a.preInit.pop()();noExitRuntime=!0;Z();


  return Module.ready
}
);
})();
if (typeof exports === 'object' && typeof module === 'object')
      module.exports = Module;
    else if (typeof define === 'function' && define['amd'])
      define([], function() { return Module; });
    else if (typeof exports === 'object')
      exports["Module"] = Module;
    